export type ReportSource = { id: string; title: string; publisher: string; publishedAt: string; url: string };
export type ReportAnalysis = {
  executiveSummary: string;
  keyPlayers: { name: string; segment: string; positioning: string; strategicSignal: string; sourceIds: string[] }[];
  trends: { title: string; detail: string; strategicImplication: string; sourceIds: string[] }[];
  risks: { title: string; detail: string; likelihood: string; impact: string; sourceIds: string[] }[];
  opportunities: { title: string; detail: string; priority: string; sourceIds: string[] }[];
  landscape: { marketDefinition: string; segments: { name: string; description: string; examples: string[] }[]; incumbentPositioning: string; challengerPositioning: string; marketSizeSignals: { signal: string; context: string; sourceIds: string[] }[] };
  executiveBrief: { headline: string; narrative: string; imperatives: string[]; clientQuestions: string[] };
};
export type ReportCompetitor = { name: string; segment: string; businessModel: string; positioning: string; strengthsJson: string; weaknessesJson: string; recentMovesJson: string; strategicSignalsJson: string };
export type MarketScanReport = { industryName: string; projectName?: string | null; scope: string; createdAt: Date | string; analysis: ReportAnalysis; sources: ReportSource[]; competitors: ReportCompetitor[] };
export type ReportSection = { heading: string; items: string[] };

const palette = { forest: "163C31", ink: "1B3029", sage: "E9F0E8", cream: "F8F5ED", gold: "B38A4B", rust: "A9533B", line: "DED6C7", muted: "68766D" };
const parsedList = (value: string) => { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : []; } catch { return []; } };
const reference = (ids: string[]) => ids.length ? ` [${ids.join(", ")}]` : "";
const text = (value: string, fallback = "No signal was generated.") => value.replace(/\s+/g, " ").trim() || fallback;

export function filenameStem(report: MarketScanReport) { return `${report.industryName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "market"}-intelligence-report`; }
export function buildReportSections(report: MarketScanReport): ReportSection[] {
  const { analysis } = report;
  return [
    { heading: "Key players", items: analysis.keyPlayers.map(item => `${item.name} — ${item.segment}. ${item.positioning} ${item.strategicSignal}${reference(item.sourceIds)}`) },
    { heading: "Emerging trends", items: analysis.trends.map(item => `${item.title}: ${item.detail} Strategic implication: ${item.strategicImplication}${reference(item.sourceIds)}`) },
    { heading: "Risks to monitor", items: analysis.risks.map(item => `${item.title}: ${item.detail} Likelihood: ${item.likelihood}; impact: ${item.impact}.${reference(item.sourceIds)}`) },
    { heading: "Strategic opportunities", items: analysis.opportunities.map(item => `${item.title}: ${item.detail} Priority: ${item.priority}.${reference(item.sourceIds)}`) },
  ].filter(section => section.items.length);
}

export async function exportMarketScanPdf(report: MarketScanReport) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ orientation: "p", unit: "pt", format: "a4" });
  const width = doc.internal.pageSize.getWidth(); const height = doc.internal.pageSize.getHeight(); const margin = 48; let y = 56;
  const addPage = () => { doc.addPage(); y = 56; };
  const ensure = (space: number) => { if (y + space > height - 48) addPage(); };
  const wrapped = (value: string, x: number, maxWidth: number, fontSize: number, color = palette.ink) => { doc.setFont("helvetica", "normal"); doc.setFontSize(fontSize); doc.setTextColor(color); const lines = doc.splitTextToSize(text(value), maxWidth); const needed = lines.length * (fontSize + 4); ensure(needed); doc.text(lines, x, y); y += needed; };
  const label = (value: string, color = palette.gold) => { ensure(18); doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.setTextColor(color); doc.text(value.toUpperCase(), margin, y); y += 18; };
  const heading = (value: string) => { ensure(30); doc.setFont("times", "bold"); doc.setFontSize(20); doc.setTextColor(palette.forest); doc.text(value, margin, y); y += 28; };
  const bullet = (value: string) => { doc.setFont("helvetica", "normal"); doc.setFontSize(9.5); doc.setTextColor(palette.ink); const lines = doc.splitTextToSize(`• ${text(value)}`, width - margin * 2 - 8); const needed = lines.length * 14 + 6; ensure(needed); doc.text(lines, margin + 4, y); y += needed; };
  doc.setFillColor(palette.forest); doc.rect(0, 0, width, 118, "F"); doc.setFont("helvetica", "bold"); doc.setFontSize(9); doc.setTextColor(palette.gold); doc.text("MARKET INTELLIGENCE REPORT", margin, 36); doc.setFont("times", "bold"); doc.setFontSize(29); doc.setTextColor("FFFFFF"); doc.text(report.analysis.executiveBrief.headline, margin, 72, { maxWidth: width - margin * 2 }); doc.setFont("helvetica", "normal"); doc.setFontSize(9); doc.setTextColor("D9E3DB"); doc.text(`${report.industryName}${report.projectName ? `  |  ${report.projectName}` : ""}  |  ${new Date(report.createdAt).toLocaleDateString()}`, margin, 102);
  y = 154; label("Research scope"); wrapped(report.scope, margin, width - margin * 2, 10, palette.muted); y += 14; label("Executive synthesis"); wrapped(report.analysis.executiveSummary, margin, width - margin * 2, 12); y += 12;
  for (const section of buildReportSections(report)) { heading(section.heading); section.items.forEach(bullet); y += 8; }
  heading("Market landscape"); label("Market definition"); wrapped(report.analysis.landscape.marketDefinition, margin, width - margin * 2, 10); y += 8; report.analysis.landscape.segments.forEach(segment => bullet(`${segment.name}: ${segment.description} Examples: ${segment.examples.join(", ")}.`)); label("Incumbent positioning", palette.forest); wrapped(report.analysis.landscape.incumbentPositioning, margin, width - margin * 2, 10); label("Challenger positioning", palette.gold); wrapped(report.analysis.landscape.challengerPositioning, margin, width - margin * 2, 10);
  heading("Consultant perspective"); wrapped(report.analysis.executiveBrief.narrative, margin, width - margin * 2, 10); label("Strategic imperatives"); report.analysis.executiveBrief.imperatives.forEach(bullet); label("Questions to resolve with the client"); report.analysis.executiveBrief.clientQuestions.forEach(bullet);
  if (report.competitors.length) { heading("Competitor profile highlights"); report.competitors.slice(0, 8).forEach(profile => { label(`${profile.name} — ${profile.segment}`, palette.forest); wrapped(`${profile.businessModel} ${profile.positioning}`, margin, width - margin * 2, 9.5); const moves = parsedList(profile.recentMovesJson); if (moves.length) bullet(`Recent move: ${moves[0]}`); }); }
  heading("Research sources"); report.sources.forEach(source => bullet(`${source.id} — ${source.title}. ${source.publisher}${source.publishedAt ? ` (${source.publishedAt})` : ""}. ${source.url}`));
  const pages = doc.getNumberOfPages(); for (let page = 1; page <= pages; page += 1) { doc.setPage(page); doc.setDrawColor(palette.line); doc.line(margin, height - 30, width - margin, height - 30); doc.setFont("helvetica", "normal"); doc.setFontSize(7.5); doc.setTextColor(palette.muted); doc.text(`${report.industryName} market intelligence  •  ${page} of ${pages}`, margin, height - 18); }
  doc.save(`${filenameStem(report)}.pdf`);
}

export async function exportMarketScanPptx(report: MarketScanReport) {
  const module = await import("pptxgenjs"); const PptxGenJS = module.default; const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE"; pptx.author = "Manus AI"; pptx.company = "Market Intelligence Platform"; pptx.subject = `${report.industryName} market intelligence`; pptx.title = `${report.industryName} market intelligence report`; pptx.theme = { headFontFace: "Aptos Display", bodyFontFace: "Aptos" };
  const slide = () => pptx.addSlide(); const addBrand = (target: ReturnType<typeof slide>, page: number) => { target.background = { color: palette.cream }; target.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: 13.333, h: 0.18, fill: { color: palette.forest }, line: { color: palette.forest } }); target.addText("MARKET INTELLIGENCE", { x: 0.55, y: 7.12, w: 2.5, h: 0.15, fontFace: "Aptos", fontSize: 6.5, bold: true, color: palette.gold }); target.addText(`${page}`, { x: 12.1, y: 7.06, w: 0.5, h: 0.2, fontFace: "Aptos", fontSize: 7, color: palette.muted, align: "right" }); };
  const addTitle = (target: ReturnType<typeof slide>, title: string, eyebrow: string) => { target.addText(eyebrow.toUpperCase(), { x: 0.58, y: 0.47, w: 7, h: 0.22, fontFace: "Aptos", fontSize: 7.5, bold: true, color: palette.gold }); target.addText(title, { x: 0.55, y: 0.78, w: 11.8, h: 0.55, fontFace: "Aptos Display", fontSize: 27, bold: true, color: palette.forest, breakLine: false, margin: 0 }); };
  const addBullets = (target: ReturnType<typeof slide>, items: string[], x: number, y: number, w: number, h: number, fontSize = 12) => target.addText(items.map(item => ({ text: text(item), options: { bullet: { indent: 12 }, hanging: 3 } })), { x, y, w, h, fontFace: "Aptos", fontSize, color: palette.ink, breakLine: true, paraSpaceAfter: 8, valign: "top", margin: 0.06, fit: "shrink" });
  let page = 1; let s = slide(); s.background = { color: palette.forest }; s.addText("MARKET INTELLIGENCE REPORT", { x: 0.68, y: 0.75, w: 5, h: 0.25, fontFace: "Aptos", fontSize: 9, bold: true, color: palette.gold }); s.addText(report.analysis.executiveBrief.headline, { x: 0.66, y: 1.25, w: 11.25, h: 1.4, fontFace: "Aptos Display", fontSize: 37, bold: true, color: "FFFFFF", margin: 0, breakLine: false, fit: "shrink" }); s.addText(`${report.industryName}${report.projectName ? `  |  ${report.projectName}` : ""}`, { x: 0.68, y: 5.83, w: 6, h: 0.25, fontFace: "Aptos", fontSize: 12, color: "D9E3DB" }); s.addText(`Prepared ${new Date(report.createdAt).toLocaleDateString()}`, { x: 0.68, y: 6.18, w: 4.5, h: 0.2, fontFace: "Aptos", fontSize: 9, color: "AFC3B6" });
  page += 1; s = slide(); addBrand(s, page); addTitle(s, "Executive synthesis", "Market scan"); s.addShape(pptx.ShapeType.roundRect, { x: 0.58, y: 1.55, w: 12.15, h: 2.25, rectRadius: 0.12, fill: { color: "FFFFFF" }, line: { color: palette.line, transparency: 30 } }); s.addText(text(report.analysis.executiveSummary), { x: 0.9, y: 1.95, w: 11.5, h: 1.45, fontFace: "Aptos Display", fontSize: 19, color: palette.ink, margin: 0, breakLine: false, fit: "shrink" }); s.addText(`Scope: ${text(report.scope)}`, { x: 0.6, y: 4.35, w: 12, h: 0.7, fontFace: "Aptos", fontSize: 12, color: palette.muted, margin: 0 }); s.addText("Signal map", { x: 0.58, y: 5.35, w: 2, h: 0.2, fontFace: "Aptos", fontSize: 8, bold: true, color: palette.gold }); ["Key players", "Emerging trends", "Risks", "Opportunities"].forEach((label, index) => { const colors = [palette.sage, "F3EBDD", "F8EAE5", "E8F1E7"]; s.addShape(pptx.ShapeType.roundRect, { x: 0.58 + index * 3.05, y: 5.75, w: 2.75, h: 0.65, rectRadius: 0.08, fill: { color: colors[index] }, line: { color: colors[index] } }); s.addText(label, { x: 0.76 + index * 3.05, y: 5.98, w: 2.3, h: 0.18, fontFace: "Aptos", fontSize: 9, bold: true, color: palette.ink, align: "center" }); });
  const fourColumnSlide = (title: string, eyebrow: string, sections: { label: string; items: string[]; color: string }[]) => { page += 1; s = slide(); addBrand(s, page); addTitle(s, title, eyebrow); sections.forEach((section, index) => { const x = 0.58 + index * 3.1; s.addShape(pptx.ShapeType.roundRect, { x, y: 1.58, w: 2.78, h: 4.9, rectRadius: 0.08, fill: { color: "FFFFFF" }, line: { color: palette.line, transparency: 20 } }); s.addShape(pptx.ShapeType.rect, { x, y: 1.58, w: 2.78, h: 0.12, fill: { color: section.color }, line: { color: section.color } }); s.addText(section.label.toUpperCase(), { x: x + 0.18, y: 1.94, w: 2.35, h: 0.18, fontFace: "Aptos", fontSize: 7.3, bold: true, color: section.color }); addBullets(s, section.items.slice(0, 5), x + 0.18, 2.28, 2.38, 3.9, 9.2); }); };
  fourColumnSlide("The signal map", "Market scan", [{ label: "Key players", items: report.analysis.keyPlayers.map(item => `${item.name}: ${item.positioning}${reference(item.sourceIds)}`), color: palette.forest }, { label: "Emerging trends", items: report.analysis.trends.map(item => `${item.title}: ${item.strategicImplication}${reference(item.sourceIds)}`), color: palette.gold }, { label: "Risks", items: report.analysis.risks.map(item => `${item.title}: ${item.detail}${reference(item.sourceIds)}`), color: palette.rust }, { label: "Opportunities", items: report.analysis.opportunities.map(item => `${item.title}: ${item.detail}${reference(item.sourceIds)}`), color: "4E805B" }]);
  page += 1; s = slide(); addBrand(s, page); addTitle(s, "Market landscape", "Competitive architecture"); s.addText(text(report.analysis.landscape.marketDefinition), { x: 0.6, y: 1.52, w: 12, h: 0.52, fontFace: "Aptos Display", fontSize: 16, color: palette.ink, margin: 0, fit: "shrink" }); report.analysis.landscape.segments.slice(0, 4).forEach((segment, index) => { const x = 0.58 + (index % 2) * 6.12; const y = 2.4 + Math.floor(index / 2) * 1.65; s.addShape(pptx.ShapeType.roundRect, { x, y, w: 5.72, h: 1.3, rectRadius: 0.08, fill: { color: index % 2 ? "F3EBDD" : "EAF2EA" }, line: { color: "FFFFFF", transparency: 100 } }); s.addText(segment.name, { x: x + 0.2, y: y + 0.18, w: 5.25, h: 0.18, fontFace: "Aptos", fontSize: 10, bold: true, color: palette.forest }); s.addText(`${text(segment.description)} Examples: ${segment.examples.join(", ")}`, { x: x + 0.2, y: y + 0.47, w: 5.2, h: 0.62, fontFace: "Aptos", fontSize: 8.5, color: palette.ink, margin: 0, fit: "shrink" }); }); s.addShape(pptx.ShapeType.roundRect, { x: 0.58, y: 5.88, w: 5.72, h: 0.75, rectRadius: 0.08, fill: { color: "FFFFFF" }, line: { color: palette.line } }); s.addText(`INCUMBENTS  ${text(report.analysis.landscape.incumbentPositioning)}`, { x: 0.78, y: 6.11, w: 5.3, h: 0.25, fontFace: "Aptos", fontSize: 8.2, color: palette.ink, margin: 0, fit: "shrink" }); s.addShape(pptx.ShapeType.roundRect, { x: 6.7, y: 5.88, w: 5.72, h: 0.75, rectRadius: 0.08, fill: { color: "FFFFFF" }, line: { color: palette.line } }); s.addText(`CHALLENGERS  ${text(report.analysis.landscape.challengerPositioning)}`, { x: 6.9, y: 6.11, w: 5.3, h: 0.25, fontFace: "Aptos", fontSize: 8.2, color: palette.ink, margin: 0, fit: "shrink" });
  page += 1; s = slide(); addBrand(s, page); addTitle(s, "Strategic perspective", "Executive brief"); s.addText(text(report.analysis.executiveBrief.narrative), { x: 0.6, y: 1.55, w: 7.25, h: 4.75, fontFace: "Aptos", fontSize: 12.5, color: palette.ink, margin: 0.03, fit: "shrink" }); s.addShape(pptx.ShapeType.roundRect, { x: 8.3, y: 1.56, w: 4.15, h: 2.1, rectRadius: 0.08, fill: { color: palette.sage }, line: { color: palette.sage } }); s.addText("STRATEGIC IMPERATIVES", { x: 8.58, y: 1.86, w: 3.5, h: 0.18, fontFace: "Aptos", fontSize: 7.4, bold: true, color: palette.forest }); addBullets(s, report.analysis.executiveBrief.imperatives, 8.56, 2.22, 3.45, 1.18, 9.5); s.addShape(pptx.ShapeType.roundRect, { x: 8.3, y: 4.0, w: 4.15, h: 2.1, rectRadius: 0.08, fill: { color: "F3EBDD" }, line: { color: "F3EBDD" } }); s.addText("CLIENT QUESTIONS", { x: 8.58, y: 4.3, w: 3.4, h: 0.18, fontFace: "Aptos", fontSize: 7.4, bold: true, color: palette.gold }); addBullets(s, report.analysis.executiveBrief.clientQuestions, 8.56, 4.66, 3.45, 1.12, 9.5);
  if (report.competitors.length) { page += 1; s = slide(); addBrand(s, page); addTitle(s, "Competitor signals", "Profile highlights"); report.competitors.slice(0, 6).forEach((profile, index) => { const x = 0.58 + (index % 3) * 4.1; const y = 1.58 + Math.floor(index / 3) * 2.35; s.addShape(pptx.ShapeType.roundRect, { x, y, w: 3.72, h: 1.92, rectRadius: 0.08, fill: { color: "FFFFFF" }, line: { color: palette.line, transparency: 15 } }); s.addText(profile.name, { x: x + 0.18, y: y + 0.18, w: 3.35, h: 0.22, fontFace: "Aptos", fontSize: 11, bold: true, color: palette.forest, margin: 0 }); s.addText(profile.segment, { x: x + 0.18, y: y + 0.5, w: 3.3, h: 0.15, fontFace: "Aptos", fontSize: 7.5, bold: true, color: palette.gold }); s.addText(text(`${profile.positioning} ${parsedList(profile.strategicSignalsJson)[0] ?? ""}`), { x: x + 0.18, y: y + 0.82, w: 3.35, h: 0.82, fontFace: "Aptos", fontSize: 8.3, color: palette.ink, margin: 0, fit: "shrink" }); }); }
  page += 1; s = slide(); addBrand(s, page); addTitle(s, "Research sources", "Traceability"); addBullets(s, report.sources.map(source => `${source.id}: ${source.title} — ${source.publisher}${source.publishedAt ? ` (${source.publishedAt})` : ""}`), 0.65, 1.55, 11.85, 4.8, 10.2); s.addText("Each analysis point in this report is grounded in the cited public-source research captured at the time of the scan.", { x: 0.65, y: 6.45, w: 10, h: 0.3, fontFace: "Aptos", fontSize: 9, italic: true, color: palette.muted, margin: 0 });
  await pptx.writeFile({ fileName: `${filenameStem(report)}.pptx` });
}
