import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, FileCheck2, FileStack, Link2, Loader2, LockKeyhole, ShieldCheck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const providers = [
  { id: "google_drive", label: "Google Drive", category: "Documents" }, { id: "sharepoint", label: "Microsoft SharePoint", category: "Documents" }, { id: "salesforce", label: "Salesforce", category: "CRM" }, { id: "hubspot", label: "HubSpot", category: "CRM" }, { id: "slack", label: "Slack", category: "Collaboration" }, { id: "teams", label: "Microsoft Teams", category: "Collaboration" },
] as const;
type Target = { type: "market_scan" | "portfolio_mandate" | "agent_run"; id: string; label: string };

export default function DeliveryHubEnhanced() {
  const utils = trpc.useUtils(); const overview = trpc.marketIntel.delivery.overview.useQuery(); const org = trpc.marketIntel.organization.summary.useQuery(); const workspace = trpc.marketIntel.workspace.useQuery(); const portfolio = trpc.marketIntel.portfolio.operations.useQuery(); const runs = trpc.marketIntel.agents.listRuns.useQuery();
  const [references, setReferences] = useState<Record<string, string>>({}); const [templateName, setTemplateName] = useState(""); const [clientLabel, setClientLabel] = useState(""); const [snapshotTarget, setSnapshotTarget] = useState(""); const [snapshotFormat, setSnapshotFormat] = useState<"pdf" | "pptx" | "markdown">("pdf");
  const configure = trpc.marketIntel.delivery.configureIntegration.useMutation({ onSuccess: () => { utils.marketIntel.delivery.overview.invalidate(); toast.success("Integration readiness updated."); }, onError: error => toast.error(error.message) });
  const validate = trpc.marketIntel.delivery.validateIntegration.useMutation({ onSuccess: (_, variables) => { setReferences(current => ({ ...current, [variables.provider]: "" })); utils.marketIntel.delivery.overview.invalidate(); toast.success("Connection recorded as verified. No credential was stored."); }, onError: error => toast.error(error.message) });
  const createTemplate = trpc.marketIntel.delivery.createTemplate.useMutation({ onSuccess: () => { setTemplateName(""); setClientLabel(""); utils.marketIntel.delivery.overview.invalidate(); toast.success("Delivery template saved."); }, onError: error => toast.error(error.message) });
  const snapshot = trpc.marketIntel.delivery.createSnapshot.useMutation({ onSuccess: () => { utils.marketIntel.delivery.overview.invalidate(); toast.success("Immutable approval snapshot recorded."); }, onError: error => toast.error(error.message) });
  const role = org.data?.active.role; const canManage = role === "owner" || role === "admin"; const canApprove = ["owner", "admin", "research_lead"].includes(role ?? "");
  const targets = useMemo<Target[]>(() => [ ...(workspace.data?.scans ?? []).map(scan => ({ type: "market_scan" as const, id: scan.id, label: `Scan · ${scan.industryName}` })), ...(portfolio.data?.mandates ?? []).map(mandate => ({ type: "portfolio_mandate" as const, id: mandate.id, label: `Mandate · ${mandate.name}` })), ...(runs.data ?? []).map(run => ({ type: "agent_run" as const, id: run.id, label: `Evidence run · ${run.question.slice(0, 48)}` })) ], [workspace.data?.scans, portfolio.data?.mandates, runs.data]);
  useEffect(() => { if (!snapshotTarget && targets.length) setSnapshotTarget(`${targets[0].type}:${targets[0].id}`); }, [snapshotTarget, targets]);
  if (overview.isLoading || org.isLoading || workspace.isLoading || portfolio.isLoading || runs.isLoading) return <div className="space-y-5"><Skeleton className="h-44 rounded-[1.5rem]" /><Skeleton className="h-96 rounded-[1.5rem]" /></div>;
  if (overview.isError) return <section className="paper-card rounded-[1.5rem] border p-10 text-center"><Link2 className="mx-auto size-7 text-[#9f733e]" /><h1 className="display-serif mt-4 text-3xl">Delivery controls are unavailable.</h1><p className="mt-2 text-sm text-muted-foreground">Refresh to retry loading the organization-private delivery ledger.</p></section>;
  const integrations = overview.data!.integrations; const snapshots = overview.data!.snapshots; const target = targets.find(item => `${item.type}:${item.id}` === snapshotTarget);
  return <div className="mx-auto max-w-7xl space-y-6"><section className="overflow-hidden rounded-[1.5rem] border border-[#cad8cc] bg-[#eaf1e8] p-6 md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[#477053]"><FileStack className="size-4" /><p className="text-[11px] font-semibold uppercase tracking-[0.18em]">Client delivery</p></div><h1 className="display-serif mt-3 max-w-3xl text-4xl leading-[0.96] text-[#193a2b] md:text-5xl">Evidence, approved and ready to deliver.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#53645b]">Safely track destination readiness, freeze client-ready evidence, and retain a citation appendix for each immutable approval.</p></div><div className="grid grid-cols-3 gap-3"><Metric value={String(integrations.filter(item => item.status === "configured").length)} label="Verified" /><Metric value={String(overview.data!.templates.length)} label="Profiles" /><Metric value={String(snapshots.length)} label="Snapshots" /></div></div></section>
    <section className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><article className="paper-card rounded-[1.5rem] border p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">External destinations</p><h2 className="mt-1 text-xl font-semibold">Connection readiness</h2></div><Badge variant="outline" className="rounded-full border-[#d8c797] bg-[#fff8e8] text-[#76572f]"><LockKeyhole className="mr-1 size-3" />No credentials stored</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{providers.map(provider => { const record = integrations.find(item => item.provider === provider.id); const reference = references[provider.id] ?? ""; return <div key={provider.id} className="rounded-xl border border-[#e0dccf] bg-[#fffdf8] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{provider.label}</p><p className="mt-1 text-xs text-muted-foreground">{provider.category}</p></div><Badge variant="outline" className={`rounded-full ${record?.status === "configured" ? "border-[#bcd2bd] bg-[#f1f8f0] text-[#376443]" : record?.status === "connection_required" ? "border-[#dfcfa7] bg-[#fffaf0] text-[#78572d]" : "text-muted-foreground"}`}>{record?.status?.replace("_", " ") ?? "not configured"}</Badge></div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-muted-foreground">{record?.displayName ?? "Not prepared"}</span>{canManage ? <Switch checked={record?.status !== "disabled"} disabled={configure.isPending} onCheckedChange={enabled => configure.mutate({ provider: provider.id, displayName: record?.displayName ?? provider.label, configuration: record?.configuration as Record<string, string> ?? {}, enabled })} /> : null}</div>{record?.status === "connection_required" && canManage ? <div className="mt-4 space-y-2 rounded-lg border border-[#e6ddc5] bg-[#fffaf0] p-3"><p className="text-xs font-semibold text-[#674b2b]">Secure connection reference</p><Input value={reference} onChange={event => setReferences(current => ({ ...current, [provider.id]: event.target.value }))} placeholder="OAuth receipt or workspace ID — never a token" className="h-9 rounded-lg text-xs" /><Button size="sm" variant="outline" className="w-full rounded-lg" disabled={reference.trim().length < 3 || validate.isPending} onClick={() => validate.mutate({ provider: provider.id, secureConnectionReference: reference })}>{validate.isPending ? <Loader2 className="mr-2 size-3 animate-spin" /> : <ShieldCheck className="mr-2 size-3" />}Mark as validated</Button></div> : null}{record?.status === "configured" ? <p className="mt-4 text-xs text-[#477455]">Verified {record.lastValidatedAt ? new Date(record.lastValidatedAt).toLocaleDateString() : "recently"}; non-secret reference retained.</p> : null}</div>; })}</div></article>
      <article className="paper-card rounded-[1.5rem] border p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-[#fff5d8] text-[#9f733e]"><FileCheck2 className="size-5" /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">Approval evidence</p><h2 className="mt-1 text-xl font-semibold">Freeze a delivery record</h2></div></div>{canApprove ? <div className="mt-5 space-y-3"><Select value={snapshotTarget} onValueChange={setSnapshotTarget}><SelectTrigger className="rounded-xl"><SelectValue placeholder="Choose evidence" /></SelectTrigger><SelectContent>{targets.map(item => <SelectItem key={`${item.type}:${item.id}`} value={`${item.type}:${item.id}`}>{item.label}</SelectItem>)}</SelectContent></Select><Select value={snapshotFormat} onValueChange={value => setSnapshotFormat(value as typeof snapshotFormat)}><SelectTrigger className="rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="pdf">PDF</SelectItem><SelectItem value="pptx">PowerPoint</SelectItem><SelectItem value="markdown">Markdown</SelectItem></SelectContent></Select><Button className="w-full rounded-xl" disabled={!target || snapshot.isPending} onClick={() => target && snapshot.mutate({ targetType: target.type, targetId: target.id, outputFormat: snapshotFormat, templateId: null })}>{snapshot.isPending ? <Loader2 className="mr-2 size-4 animate-spin" /> : <ShieldCheck className="mr-2 size-4" />}Approve immutable snapshot</Button></div> : <p className="mt-5 rounded-xl bg-muted/50 p-4 text-sm text-muted-foreground">Approval is limited to organization owners, administrators, and research leads.</p>}<div className="mt-6 border-t pt-5"><p className="text-sm font-semibold">Create delivery profile</p>{canApprove ? <div className="mt-3 space-y-3"><Input value={templateName} onChange={event => setTemplateName(event.target.value)} placeholder="Template name" className="rounded-xl" /><Input value={clientLabel} onChange={event => setClientLabel(event.target.value)} placeholder="Client label" className="rounded-xl" /><Button variant="outline" className="w-full rounded-xl" disabled={templateName.trim().length < 2 || clientLabel.trim().length < 2 || createTemplate.isPending} onClick={() => createTemplate.mutate({ name: templateName, clientLabel, templateKind: "executive_brief", brandName: org.data?.active.name ?? "Market Intelligence", accentColor: "#173a33", executiveIntro: "Approved research evidence prepared for client review.", includeCitationAppendix: true })}>{createTemplate.isPending ? "Saving…" : "Save profile"}</Button></div> : null}</div></article></section>
    <section className="paper-card rounded-[1.5rem] border p-6"><div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">Approval ledger</p><h2 className="mt-1 text-xl font-semibold">Immutable evidence snapshots</h2></div><CheckCircle2 className="size-5 text-[#477455]" /></div><div className="mt-5 grid gap-3 md:grid-cols-2">{snapshots.length ? snapshots.map(item => <div key={item.id} className="rounded-xl border border-[#d8e4d7] bg-[#f7fbf6] p-4"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Badge variant="outline" className="border-[#bdd2be] bg-white text-[#477455]">{item.outputFormat.toUpperCase()}</Badge><p className="text-sm font-semibold">{item.targetType.replace("_", " ")}</p></div><span className="text-xs text-muted-foreground">{new Date(item.approvedAt).toLocaleDateString()}</span></div><p className="mt-2 font-mono text-[10px] text-muted-foreground">Digest {item.contentDigest.slice(0, 18)}…</p>{item.citationAppendix?.length ? <details className="mt-3 rounded-lg border border-[#dce7da] bg-white/70 p-3"><summary className="cursor-pointer text-xs font-semibold text-[#426b4c]">Source-citation appendix · {item.citationAppendix.length} items</summary><ul className="mt-3 space-y-2 text-xs text-muted-foreground">{item.citationAppendix.map((citation, index) => <li key={`${citation.label}-${index}`}>{citation.url ? <a href={citation.url} target="_blank" rel="noreferrer" className="text-[#426b4c] underline underline-offset-2">{citation.label}</a> : citation.label}</li>)}</ul></details> : null}</div>) : <div className="rounded-xl border border-dashed p-7 text-center md:col-span-2"><FileCheck2 className="mx-auto size-5 text-[#9f733e]" /><p className="mt-3 text-sm text-muted-foreground">No delivery snapshot has been approved.</p></div>}</div></section>
  </div>;
}
function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl border border-[#bfd2c0] bg-white/70 px-3 py-3"><p className="display-serif text-xl text-[#244b34]">{value}</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-[0.12em] text-[#607566]">{label}</p></div>; }
