import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Bot, CheckCircle2, CircleAlert, GitFork, Radar, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const assessmentStyle: Record<string, string> = { corroborated: "border-[#bfd0c1] bg-[#eef5ec] text-[#356246]", supported: "border-[#c7d6d4] bg-[#eff7f7] text-[#32636a]", conflicted: "border-[#d8bfb4] bg-[#fff3ef] text-[#a24f39]", insufficient: "border-[#d7c89f] bg-[#fff5d8] text-[#785d27]" };
const dateLabel = (value: Date | string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));

export default function EvidenceAgents() {
  const utils = trpc.useUtils();
  const workspace = trpc.marketIntel.workspace.useQuery();
  const runs = trpc.marketIntel.agents.listRuns.useQuery();
  const [selectedScanIds, setSelectedScanIds] = useState<string[]>([]);
  const [question, setQuestion] = useState("Where is the strongest evidence of strategic convergence, and what conflicts should we resolve before advising a client?");
  const scans = workspace.data?.scans ?? [];
  const selected = useMemo(() => scans.filter(scan => selectedScanIds.includes(scan.id)), [scans, selectedScanIds]);
  const runEvidence = trpc.marketIntel.agents.runEvidence.useMutation({ onSuccess: () => { utils.marketIntel.agents.listRuns.invalidate(); toast.success("Evidence agents completed their research run."); }, onError: error => toast.error(error.message) });
  const toggleScan = (id: string) => setSelectedScanIds(ids => ids.includes(id) ? ids.filter(scanId => scanId !== id) : ids.length >= 6 ? ids : [...ids, id]);
  const latestRun = runs.data?.[0];
  if (workspace.isLoading || runs.isLoading) return <div className="space-y-6"><Skeleton className="h-52 rounded-[1.75rem]" /><Skeleton className="h-[32rem] rounded-[1.75rem]" /></div>;
  if (workspace.isError || runs.isError) return <section className="paper-card rounded-[1.75rem] border p-10 text-center"><Radar className="mx-auto size-6 text-[#9f733e]" /><h1 className="display-serif mt-4 text-3xl">Evidence agents are unavailable.</h1><p className="mt-2 text-sm text-muted-foreground">Refresh the page to retrieve your private research context and recent runs.</p></section>;
  return <div className="space-y-7">
    <section className="paper-card relative overflow-hidden rounded-[1.75rem] border p-7 md:p-10"><div className="absolute -right-12 -top-14 size-64 rounded-full bg-[#e6cc83]/20 blur-3xl" /><div className="relative max-w-3xl"><p className="flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#9f733e]"><Bot className="size-3.5" /> Evidence agent orchestration</p><h1 className="display-serif mt-4 text-4xl leading-[0.95] md:text-5xl">Interrogate the source layer, not just the summary.</h1><p className="mt-5 text-sm leading-6 text-muted-foreground">A verification agent tests decision-relevant claims against selected private scans. A second synthesis agent converts only validated claim packets into an executive answer, surfacing conflict and evidence gaps plainly.</p></div></section>
    <section className="grid gap-6 xl:grid-cols-[.86fr_1.14fr]"><article className="paper-card rounded-[1.5rem] border p-6"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">Research run</p><h2 className="mt-2 text-2xl font-semibold">Choose the evidence set</h2><div className="mt-5 max-h-60 space-y-2 overflow-y-auto pr-1">{scans.length ? scans.map(scan => <label key={scan.id} className={`flex cursor-pointer gap-3 rounded-xl border p-3 transition-colors ${selectedScanIds.includes(scan.id) ? "border-[#c9a861] bg-[#fffaf0]" : "bg-[#fffdf8] hover:border-[#c9a861]"}`}><Checkbox checked={selectedScanIds.includes(scan.id)} onCheckedChange={() => toggleScan(scan.id)} /><span className="min-w-0"><span className="block text-sm font-semibold">{scan.industryName}</span><span className="mt-1 block line-clamp-2 text-xs leading-5 text-muted-foreground">{scan.scope}</span></span></label>) : <p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Create a market scan before running the evidence agents.</p>}</div><p className="mt-3 text-xs text-muted-foreground">{selected.length}/6 scans selected</p><Label className="mt-5 block text-xs font-semibold uppercase tracking-[0.13em] text-muted-foreground">Decision question</Label><Textarea value={question} onChange={event => setQuestion(event.target.value)} className="mt-2 min-h-32 rounded-xl" placeholder="What evidence should the agents triangulate?" /><Button disabled={selected.length === 0 || question.trim().length < 12 || runEvidence.isPending} onClick={() => runEvidence.mutate({ scanIds: selectedScanIds, question })} className="mt-4 w-full rounded-xl bg-primary text-primary-foreground hover:bg-primary/90"><Sparkles className="mr-2 size-4" />{runEvidence.isPending ? "Verifying evidence…" : "Run evidence agents"}</Button></article>
      <article className="paper-card rounded-[1.5rem] border p-6">{latestRun ? <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">Latest completed run</p><h2 className="mt-2 text-2xl font-semibold">Validated synthesis</h2><p className="mt-2 text-xs text-muted-foreground">{dateLabel(latestRun.createdAt)} · {latestRun.model}</p></div><Badge className="w-fit rounded-full bg-[#173a33] px-3 py-1.5 text-[#f7f3e9] hover:bg-[#173a33]">{latestRun.claims.length} claims</Badge></div><div className="mt-5 whitespace-pre-wrap rounded-xl border bg-[#fffdf8] p-5 text-sm leading-7 text-[#485a50]">{latestRun.synthesis}</div><div className="mt-6"><div className="flex items-center gap-2"><GitFork className="size-4 text-[#9f733e]" /><h3 className="text-sm font-semibold">Claim-level evidence graph</h3></div><div className="mt-3 space-y-3">{latestRun.claims.map(claim => <div key={claim.id} className="rounded-xl border bg-background p-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-semibold">{claim.claim}</p><Badge variant="outline" className={`rounded-full ${assessmentStyle[claim.assessment]}`}>{claim.assessment}</Badge></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{claim.rationale}</p><div className="mt-3 flex flex-wrap gap-2 text-[11px]"><span className="rounded-full bg-muted px-2 py-1">Confidence {claim.confidence}%</span>{claim.sourceIds.map(id => <span key={id} className="rounded-full bg-[#eef5ec] px-2 py-1 text-[#356246]">{id}</span>)}{claim.counterSourceIds.map(id => <span key={id} className="rounded-full bg-[#fff3ef] px-2 py-1 text-[#a24f39]">Counter: {id}</span>)}</div></div>)}</div></div></> : <div className="flex min-h-[34rem] flex-col items-center justify-center text-center"><CircleAlert className="size-6 text-[#9f733e]" /><h2 className="display-serif mt-4 text-3xl">No evidence run yet.</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">Select one or more private scans and pose a decision question. Claims will be retained with evidence status and confidence for review.</p></div>}</article></section>
  </div>;
}
