import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Archive, Clock3, LockKeyhole, ScrollText, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type PolicyForm = { researchRetentionDays: number; knowledgeRetentionDays: number; auditRetentionDays: number; legalHoldEnabled: boolean };
const initialPolicy: PolicyForm = { researchRetentionDays: 730, knowledgeRetentionDays: 1095, auditRetentionDays: 1095, legalHoldEnabled: false };
const labelEvent = (value: string) => value.replace(/[._]/g, " ").replace(/\b\w/g, letter => letter.toUpperCase());
const formatDate = (date: Date | string | null) => date ? new Date(date).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : "Not yet updated";

export default function Governance() {
  const utils = trpc.useUtils();
  const organization = trpc.marketIntel.organization.summary.useQuery();
  const isAdministrator = organization.data?.active.role === "owner" || organization.data?.active.role === "admin";
  const overview = trpc.marketIntel.governance.overview.useQuery(undefined, { enabled: isAdministrator, retry: false });
  const [policy, setPolicy] = useState<PolicyForm>(initialPolicy);
  useEffect(() => { if (overview.data?.policy) setPolicy({ researchRetentionDays: overview.data.policy.researchRetentionDays, knowledgeRetentionDays: overview.data.policy.knowledgeRetentionDays, auditRetentionDays: overview.data.policy.auditRetentionDays, legalHoldEnabled: overview.data.policy.legalHoldEnabled }); }, [overview.data?.policy]);
  const savePolicy = trpc.marketIntel.governance.updateRetention.useMutation({ onSuccess: () => { toast.success("Retention policy saved and recorded in the audit trail."); utils.marketIntel.governance.overview.invalidate(); }, onError: error => toast.error(error.message) });

  if (organization.isLoading) return <div className="space-y-6"><Skeleton className="h-52 rounded-[1.75rem]" /><Skeleton className="h-96 rounded-[1.75rem]" /></div>;
  if (organization.isError) return <GovernanceError title="Organization context is unavailable." detail={organization.error.message} retry={() => organization.refetch()} />;
  if (!isAdministrator) return <div className="space-y-7"><section className="paper-card relative overflow-hidden rounded-[1.75rem] border p-8 md:p-10"><div className="absolute -right-10 -top-12 size-56 rounded-full bg-[#e6cc83]/20 blur-3xl" /><div className="relative max-w-2xl"><div className="mb-4 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#9f733e]"><LockKeyhole className="size-3.5" /> Governance workspace</div><h1 className="display-serif text-4xl leading-[0.95] md:text-5xl">Access restricted.</h1><p className="mt-5 text-sm leading-6 text-muted-foreground">Governance controls and organization audit trails are available only to organization owners and administrators. Your current role does not permit policy review or changes.</p></div></section><section className="paper-card flex items-start gap-4 rounded-[1.5rem] border p-6"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#fff5d8] text-[#9f733e]"><ShieldCheck className="size-5" /></span><div><h2 className="font-semibold">Protected control plane</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Ask an organization owner or administrator if you need a retention-policy decision or an audit review.</p></div></section></div>;
  if (overview.isLoading) return <div className="space-y-6"><Skeleton className="h-52 rounded-[1.75rem]" /><Skeleton className="h-[32rem] rounded-[1.75rem]" /></div>;
  if (overview.isError || !overview.data) return <GovernanceError title="Governance records are unavailable." detail={overview.error?.message ?? "The governance overview did not return a usable response."} retry={() => overview.refetch()} />;

  const daysInput = (field: keyof Pick<PolicyForm, "researchRetentionDays" | "knowledgeRetentionDays" | "auditRetentionDays">, min: number) => <Input type="number" min={min} max={3650} value={policy[field]} onChange={event => setPolicy(current => ({ ...current, [field]: Math.min(3650, Math.max(min, Number(event.target.value) || min)) }))} className="mt-2 h-11 rounded-xl" />;
  const dirty = policy.researchRetentionDays !== overview.data.policy.researchRetentionDays || policy.knowledgeRetentionDays !== overview.data.policy.knowledgeRetentionDays || policy.auditRetentionDays !== overview.data.policy.auditRetentionDays || policy.legalHoldEnabled !== overview.data.policy.legalHoldEnabled;

  return <div className="space-y-7">
    <section className="paper-card relative overflow-hidden rounded-[1.75rem] border p-7 md:p-10"><div className="absolute -right-10 -top-12 size-56 rounded-full bg-[#e6cc83]/20 blur-3xl" /><div className="relative flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div className="max-w-3xl"><div className="mb-4 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#9f733e]"><LockKeyhole className="size-3.5" /> Organization governance</div><h1 className="display-serif text-4xl leading-[0.95] md:text-5xl">Govern the research boundary.</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-muted-foreground">Review sensitive organization activity and set the lifecycle rules that protect research, reusable knowledge, and audit evidence.</p></div><div className="flex flex-wrap gap-2"><Badge className="rounded-full bg-[#173a33] px-3 py-1.5 text-[#f7f3e9] hover:bg-[#173a33]"><ShieldCheck className="mr-1.5 size-3.5" /> Administrator access</Badge><Badge variant="outline" className="rounded-full px-3 py-1.5">{overview.data.events.length} recent events</Badge></div></div></section>

    <section className="grid gap-6 xl:grid-cols-[0.94fr_1.06fr]">
      <article className="paper-card rounded-[1.5rem] border p-6"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#e9f0eb] text-primary"><Archive className="size-5" /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">Retention policy</p><h2 className="mt-1 text-xl font-semibold">Control evidence lifecycles</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Set how long organization-scoped information remains eligible for retention. A legal hold blocks routine lifecycle actions while enabled.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><label><Label className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Research days</Label>{daysInput("researchRetentionDays", 30)}</label><label><Label className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Knowledge days</Label>{daysInput("knowledgeRetentionDays", 30)}</label><label><Label className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Audit days</Label>{daysInput("auditRetentionDays", 365)}</label></div><div className="mt-5 flex items-center justify-between gap-5 rounded-2xl border bg-[#fffdf8] p-4"><div><p className="text-sm font-semibold">Legal hold</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Preserve records beyond scheduled retention actions.</p></div><Switch checked={policy.legalHoldEnabled} onCheckedChange={legalHoldEnabled => setPolicy(current => ({ ...current, legalHoldEnabled }))} aria-label="Enable legal hold" /></div>{policy.legalHoldEnabled && <p className="mt-4 flex gap-2 rounded-xl bg-[#fff5d8] p-3 text-xs leading-5 text-[#785d27]"><AlertTriangle className="mt-0.5 size-3.5 shrink-0" />Legal hold is active. Retention durations remain visible, but should not drive routine deletion while the hold is in force.</p>}<div className="mt-5 flex items-center justify-between gap-4"><p className="text-xs text-muted-foreground">Last policy change: {formatDate(overview.data.policy.updatedAt)}</p><Button disabled={!dirty || savePolicy.isPending} onClick={() => savePolicy.mutate(policy)} className="rounded-xl bg-primary text-primary-foreground hover:bg-primary/90">{savePolicy.isPending ? "Saving…" : "Save policy"}</Button></div></article>
      <article className="paper-card rounded-[1.5rem] border p-6"><div className="flex items-start gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#fff5d8] text-[#9f733e]"><ShieldCheck className="size-5" /></span><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">Control posture</p><h2 className="mt-1 text-xl font-semibold">Policy at a glance</h2></div></div><div className="mt-6 space-y-3"><div className="flex items-center justify-between rounded-2xl bg-muted/45 px-4 py-3"><span className="text-sm text-muted-foreground">Research records</span><span className="font-semibold">{policy.researchRetentionDays.toLocaleString()} days</span></div><div className="flex items-center justify-between rounded-2xl bg-muted/45 px-4 py-3"><span className="text-sm text-muted-foreground">Knowledge assets</span><span className="font-semibold">{policy.knowledgeRetentionDays.toLocaleString()} days</span></div><div className="flex items-center justify-between rounded-2xl bg-muted/45 px-4 py-3"><span className="text-sm text-muted-foreground">Audit evidence</span><span className="font-semibold">{policy.auditRetentionDays.toLocaleString()} days</span></div><div className="flex items-center justify-between rounded-2xl border px-4 py-3"><span className="text-sm text-muted-foreground">Legal hold</span><Badge variant="outline" className={policy.legalHoldEnabled ? "border-[#caa757] bg-[#fff5d8] text-[#785d27]" : ""}>{policy.legalHoldEnabled ? "Enabled" : "Not active"}</Badge></div></div><p className="mt-5 text-xs leading-5 text-muted-foreground">Policy configuration is organization-private and every saved change is captured in the audit trail.</p></article>
    </section>

    <section className="paper-card overflow-hidden rounded-[1.5rem] border"><div className="flex flex-col gap-3 border-b px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">Audit trail</p><h2 className="mt-1 text-xl font-semibold">Recent sensitive activity</h2><p className="mt-1 text-sm text-muted-foreground">The latest {overview.data.events.length} organization-scoped events, newest first.</p></div><ScrollText className="size-5 text-muted-foreground" /></div>{overview.data.events.length === 0 ? <div className="px-6 py-16 text-center"><span className="mx-auto flex size-11 items-center justify-center rounded-2xl bg-[#e9f0eb] text-primary"><Clock3 className="size-5" /></span><h3 className="mt-4 font-semibold">No sensitive activity has been recorded yet.</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">Membership, monitoring, knowledge, portfolio, export, and governance events will appear here as the organization uses those capabilities.</p></div> : <div className="divide-y">{overview.data.events.map(event => <div key={event.id} className="grid gap-3 px-6 py-5 md:grid-cols-[minmax(0,1.3fr)_minmax(0,.85fr)_minmax(0,1fr)] md:items-center"><div className="min-w-0"><p className="font-medium">{labelEvent(event.eventType)}</p><p className="mt-1 text-xs text-muted-foreground">{event.resourceType}{event.resourceId ? ` · ${event.resourceId}` : ""}</p></div><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Actor</p><p className="mt-1 text-sm">User #{event.actorUserId}</p></div><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground">Recorded</p><p className="mt-1 text-sm">{formatDate(event.createdAt)}</p>{Object.keys(event.metadata).length > 0 && <p className="mt-1 truncate text-xs text-muted-foreground">{Object.entries(event.metadata).map(([key, value]) => `${key}: ${String(value)}`).join(" · ")}</p>}</div></div>)}</div>}</section>
  </div>;
}

function GovernanceError({ title, detail, retry }: { title: string; detail: string; retry: () => void }) {
  return <section className="paper-card rounded-[1.75rem] border p-8 text-center md:p-10"><span className="mx-auto flex size-11 items-center justify-center rounded-2xl bg-[#fff5d8] text-[#9f733e]"><AlertTriangle className="size-5" /></span><h1 className="display-serif mt-5 text-3xl">{title}</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-muted-foreground">{detail}</p><Button variant="outline" onClick={retry} className="mt-6 rounded-xl">Try again</Button></section>;
}
