import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowRight, BellRing, BookOpenText, ChevronDown, FileText, FolderOpen, Search, Sparkles } from "lucide-react";
import { useLocation } from "wouter";

const dateLabel = (value: Date | string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric" }).format(new Date(value));

export default function HomeCompact() {
  const { user } = useAuth(); const [, setLocation] = useLocation(); const dashboard = trpc.marketIntel.dashboard.useQuery(); const monitoring = trpc.marketIntel.monitoring.alerts.useQuery(); const data = dashboard.data; const recentScans = data?.scans.slice(0, 3) ?? []; const topIndustries = data?.industries.slice(0, 4) ?? [];
  return <div className="mx-auto max-w-7xl space-y-4">
    <section className="overflow-hidden rounded-[1.5rem] border border-[#d9d1be] bg-[#f1eee4] p-5 md:p-6"><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div><div className="flex items-center gap-2 text-[#99703c]"><Sparkles className="size-3.5" /><p className="text-[10px] font-semibold uppercase tracking-[0.18em]">Intelligence desk</p></div><h1 className="display-serif mt-3 max-w-2xl text-3xl leading-[0.98] text-[#1c342d] md:text-4xl">Your next client decision, made visible.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#52635b]">Welcome back{user?.name ? `, ${user.name.split(" ")[0]}` : ""}. Continue a live perspective or begin a fresh market question.</p><div className="mt-5 flex flex-wrap gap-2"><Button onClick={() => setLocation("/new")} className="rounded-xl bg-[#173a33] px-4 text-[#f7f3e9] hover:bg-[#234b42]"><Search className="mr-2 size-3.5" />New research</Button><Button variant="outline" onClick={() => setLocation("/executive-briefings")} className="rounded-xl border-[#cfc0a1] bg-white/50 text-[#345146] hover:bg-white"><FileText className="mr-2 size-3.5" />Executive briefings</Button></div></div><div className="grid grid-cols-2 gap-2 self-end">{dashboard.isLoading || monitoring.isLoading ? <><Skeleton className="h-[78px] rounded-xl" /><Skeleton className="h-[78px] rounded-xl" /><Skeleton className="h-[78px] rounded-xl" /><Skeleton className="h-[78px] rounded-xl" /></> : <><CompactMetric value={data?.scans.length ?? 0} label="Recent scans" onClick={() => setLocation("/workspace")} /><CompactMetric value={monitoring.data?.unreadCount ?? 0} label="Needs review" accent onClick={() => setLocation("/monitoring")} /><CompactMetric value={data?.industries.length ?? 0} label="Tracked markets" onClick={() => setLocation("/industries")} /><CompactMetric value={data?.briefs.length ?? 0} label="Reusable briefs" onClick={() => setLocation("/workspace")} /></>}</div></div></section>
    <section className="grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><article className="paper-card rounded-[1.25rem] border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#947044]">Continue where you left off</p><h2 className="display-serif mt-1 text-2xl">Active perspectives</h2></div><button onClick={() => setLocation("/workspace")} className="mt-1 flex shrink-0 items-center gap-1 text-xs font-semibold text-primary hover:underline">All research <ArrowRight className="size-3.5" /></button></div>{dashboard.isLoading ? <div className="mt-4 space-y-2"><Skeleton className="h-16 rounded-xl" /><Skeleton className="h-16 rounded-xl" /></div> : recentScans.length ? <div className="mt-3 divide-y divide-border">{recentScans.map((scan, index) => <button key={scan.id} onClick={() => setLocation(`/workspace/${scan.id}`)} className="group flex w-full items-center justify-between gap-4 py-3 text-left first:pt-2"><div className="min-w-0"><div className="flex items-center gap-2"><span className="flex size-5 shrink-0 items-center justify-center rounded-full bg-[#edf2ec] text-[10px] font-semibold text-[#42684c]">{index + 1}</span><Badge variant="outline" className="border-[#d9caa8] bg-[#fcf9f1] text-[10px] font-medium text-[#76572f]">{scan.industryName}</Badge><span className="text-[10px] text-muted-foreground">{dateLabel(scan.createdAt)}</span></div><p className="mt-1.5 line-clamp-1 text-sm font-semibold text-foreground">{scan.executiveSummary}</p></div><ArrowRight className="size-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-primary" /></button>)}</div> : <CompactEmpty icon={Search} title="No scans yet" body="Start a focused market question and it will appear here." action="Launch research" onClick={() => setLocation("/new")} />}</article>
      <article className="rounded-[1.25rem] border border-[#214c41] bg-[#173a33] p-5 text-[#f4f0e7]"><div className="flex items-center justify-between"><span className="flex size-9 items-center justify-center rounded-xl bg-[#e6cc83] text-[#173a33]"><BellRing className="size-4" /></span><button onClick={() => setLocation("/monitoring")} className="text-xs font-semibold text-[#e6cc83] hover:underline">Open monitoring</button></div><p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.17em] text-[#d5bd7d]">Triage now</p><p className="display-serif mt-1 text-3xl leading-none">{monitoring.data?.unreadCount ?? 0} material signals need your attention.</p><p className="mt-3 text-xs leading-5 text-[#cbd8cf]">Review alert changes, then decide whether they belong in a portfolio view or client-ready brief.</p><div className="mt-5 border-t border-white/15 pt-4"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#b9cfc0]">Markets in focus</p><div className="mt-2 flex flex-wrap gap-1.5">{topIndustries.length ? topIndustries.map(industry => <button key={industry.id} onClick={() => setLocation("/industries")} className="rounded-lg bg-white/10 px-2.5 py-1.5 text-[11px] font-medium text-[#eef3ee] transition-colors hover:bg-white/15">{industry.industryName}</button>) : <span className="text-xs text-[#cbd8cf]">Add tracked industries to make this useful.</span>}</div></div></article></section>
    <details className="group paper-card rounded-[1.25rem] border bg-card"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-4 text-left"><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#947044]">More context</p><p className="mt-1 text-sm font-semibold">Research library, watchlist, and reusable perspectives</p></div><ChevronDown className="size-4 text-muted-foreground transition-transform group-open:rotate-180" /></summary><div className="grid gap-4 border-t border-border p-4 md:grid-cols-2"><section><div className="flex items-center justify-between"><p className="text-xs font-semibold">Tracked markets</p><button onClick={() => setLocation("/industries")} className="text-xs font-semibold text-primary hover:underline">Manage</button></div><div className="mt-3 flex flex-wrap gap-2">{data?.industries.length ? data.industries.slice(0, 8).map(industry => <button key={industry.id} onClick={() => setLocation("/new")} className="rounded-lg border border-[#ded6c2] bg-[#fcfaf4] px-2.5 py-1.5 text-xs font-medium transition-colors hover:bg-[#f2ecdd]">{industry.industryName}</button>) : <p className="text-xs leading-5 text-muted-foreground">Your market watchlist is empty.</p>}</div></section><section><div className="flex items-center justify-between"><p className="text-xs font-semibold">Reusable brief library</p><button onClick={() => setLocation("/workspace")} className="text-xs font-semibold text-primary hover:underline">Open library</button></div><div className="mt-2 divide-y">{data?.briefs.length ? data.briefs.slice(0, 3).map(brief => <button key={brief.id} onClick={() => setLocation(`/workspace/${brief.scanId}`)} className="flex w-full items-center justify-between gap-3 py-2 text-left"><span className="line-clamp-1 text-xs font-medium">{brief.title}</span><ArrowRight className="size-3.5 shrink-0 text-muted-foreground" /></button>) : <p className="py-2 text-xs leading-5 text-muted-foreground">Save an industry perspective to build a reusable library.</p>}</div></section></div></details>
  </div>;
}

function CompactMetric({ value, label, onClick, accent = false }: { value: number; label: string; onClick: () => void; accent?: boolean }) { return <button onClick={onClick} className={`rounded-xl border px-3 py-3 text-left transition-colors hover:bg-white ${accent ? "border-[#dbbe78] bg-[#fff5d8]" : "border-[#d7d5cd] bg-white/60"}`}><p className="display-serif text-2xl leading-none text-[#244b34]">{value}</p><p className="mt-1.5 text-[9px] font-semibold uppercase tracking-[0.12em] text-[#69796e]">{label}</p></button>; }
function CompactEmpty({ icon: Icon, title, body, action, onClick }: { icon: typeof Search; title: string; body: string; action: string; onClick: () => void }) { return <div className="mt-4 rounded-xl border border-dashed border-[#d8cfbc] bg-[#fbfaf5] p-5 text-center"><Icon className="mx-auto size-4 text-[#9d7c52]" /><p className="mt-2 text-sm font-semibold">{title}</p><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-muted-foreground">{body}</p><button onClick={onClick} className="mt-3 text-xs font-semibold text-primary hover:underline">{action}</button></div>; }
