import { startLogin } from "@/const";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { BellRing, Check, ChevronRight, ClipboardCheck, Compass, LockKeyhole, Radar, TriangleAlert } from "lucide-react";
import { useMemo, useState } from "react";

type Tab = "brief" | "alerts" | "approvals";
const mandateTone: Record<string, string> = { scoping: "bg-[#eaf3f3] text-[#34636b]", active: "bg-[#edf5ec] text-[#356246]", at_risk: "bg-[#fff0ec] text-[#a24f39]", complete: "bg-[#f1f0eb] text-[#596259]" };

export default function MobileCompanion() {
  const { loading, user } = useAuth(); const utils = trpc.useUtils(); const notifications = trpc.marketIntel.collaboration.notifications.useQuery(undefined, { enabled: Boolean(user) }); const operations = trpc.marketIntel.portfolio.operations.useQuery(undefined, { enabled: Boolean(user) }); const delivery = trpc.marketIntel.delivery.overview.useQuery(undefined, { enabled: Boolean(user) }); const executive = trpc.marketIntel.executive.overview.useQuery(undefined, { enabled: Boolean(user) }); const [tab, setTab] = useState<Tab>("brief"); const markRead = trpc.marketIntel.collaboration.markNotificationRead.useMutation({ onSuccess: () => utils.marketIntel.collaboration.notifications.invalidate() });
  const unread = useMemo(() => (notifications.data ?? []).filter(item => item.status === "unread"), [notifications.data]); const activeMandates = useMemo(() => (operations.data?.mandates ?? []).filter(item => item.status === "active" || item.status === "at_risk"), [operations.data?.mandates]); const escalations = useMemo(() => (operations.data?.watchlists ?? []).filter(item => item.status === "escalated"), [operations.data?.watchlists]); const distributedBriefings = useMemo(() => (executive.data?.briefings ?? []).filter(item => item.reviewStatus === "distributed"), [executive.data?.briefings]);
  if (loading) return <div className="min-h-screen bg-[#f7f5ef] p-5"><Skeleton className="h-24 rounded-[1.5rem]" /><Skeleton className="mt-5 h-96 rounded-[1.5rem]" /></div>;
  if (!user) return <main className="flex min-h-screen items-center justify-center bg-[#173a33] p-6"><section className="w-full max-w-sm rounded-[2rem] bg-[#f7f5ef] p-7 text-center"><span className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-[#e6cc83] text-[#173a33]"><Compass className="size-5" /></span><p className="mt-6 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#9f733e]">Mobile companion</p><h1 className="display-serif mt-3 text-4xl leading-none">Your intelligence, in motion.</h1><p className="mt-5 text-sm leading-6 text-muted-foreground">Sign in to review private collaboration signals, mandate health, and client-delivery approvals.</p><Button onClick={startLogin} className="mt-7 w-full rounded-xl bg-[#173a33] text-white">Sign in</Button></section></main>;
  if (notifications.isLoading || operations.isLoading || delivery.isLoading || executive.isLoading) return <div className="min-h-screen bg-[#f7f5ef] p-5"><Skeleton className="h-32 rounded-[1.5rem]" /><Skeleton className="mt-5 h-96 rounded-[1.5rem]" /></div>;
  return <main className="min-h-screen bg-[#f7f5ef] pb-28 text-[#193a2b]"><header className="bg-[#173a33] px-5 pb-8 pt-7 text-[#f7f5ef]"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-[#d9c677]">Mobile companion</p><h1 className="display-serif mt-2 text-3xl">Good to see you, {user.name?.split(" ")[0] || "consultant"}.</h1></div><span className="flex size-10 items-center justify-center rounded-2xl bg-white/10"><Compass className="size-5" /></span></div><p className="mt-4 max-w-sm text-sm leading-6 text-[#c5d3c8]">Triage the work that needs your attention before the next client conversation.</p><div className="mt-6 grid grid-cols-3 gap-2"><Metric value={String(unread.length)} label="Unread" /><Metric value={String(activeMandates.length)} label="Mandates" /><Metric value={String(escalations.length)} label="Escalations" /></div></header>
    <section className="mx-auto -mt-2 max-w-md px-4"><div className="rounded-[1.5rem] border border-[#ded8c9] bg-white p-1.5 shadow-sm"><div className="grid grid-cols-3 gap-1">{(["brief", "alerts", "approvals"] as Tab[]).map(item => <button key={item} onClick={() => setTab(item)} className={`rounded-xl px-2 py-2.5 text-xs font-semibold capitalize transition-colors ${tab === item ? "bg-[#e6cc83] text-[#173a33]" : "text-[#69766e]"}`}>{item}</button>)}</div></div>
      {tab === "brief" ? <div className="mt-5 space-y-4"><SectionHeading icon={<Radar className="size-4" />} eyebrow="Today’s portfolio" title="Mandate health" /><div className="space-y-3">{activeMandates.length ? activeMandates.map(mandate => <article key={mandate.id} className="rounded-[1.35rem] border border-[#dfded7] bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{mandate.name}</p><p className="mt-1 text-xs text-muted-foreground">{mandate.clientLabel} · Owner #{mandate.ownerUserId}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] ${mandateTone[mandate.status]}`}>{mandate.status.replace("_", " ")}</span></div><p className="mt-3 line-clamp-2 text-xs leading-5 text-[#5c6b62]">{mandate.description}</p><div className="mt-3 flex items-center gap-2 text-xs text-[#9f733e]"><ChevronRight className="size-3.5" />Review in Portfolio</div></article>) : <Empty icon={<Compass className="size-5" />} text="No active client mandates yet." />}</div>{escalations.length ? <><SectionHeading icon={<TriangleAlert className="size-4" />} eyebrow="Escalations" title="Watchlist signals" /><div className="space-y-3">{escalations.map(item => <article key={item.id} className="rounded-[1.35rem] border border-[#f0cfc4] bg-[#fff8f5] p-4"><p className="font-semibold text-[#7f3d2c]">{item.label}</p><p className="mt-2 text-xs leading-5 text-[#7f5649]">{item.rationale}</p></article>)}</div></> : null}</div> : null}
      {tab === "alerts" ? <div className="mt-5 space-y-4"><SectionHeading icon={<BellRing className="size-4" />} eyebrow="Collaboration inbox" title="Signals for you" />{unread.length ? unread.map(item => <button key={item.id} onClick={() => markRead.mutate({ id: item.id })} className="w-full rounded-[1.35rem] border border-[#dfded7] bg-white p-4 text-left shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.title}</p><p className="mt-2 line-clamp-3 text-xs leading-5 text-muted-foreground">{item.body}</p></div><span className="mt-1 size-2 shrink-0 rounded-full bg-[#d29f46]" /></div><p className="mt-4 flex items-center gap-1.5 text-xs font-semibold text-[#8d6732]"><Check className="size-3.5" />Mark read</p></button>) : <Empty icon={<BellRing className="size-5" />} text="Your private collaboration inbox is clear." />}</div> : null}
      {tab === "approvals" ? <div className="mt-5 space-y-4"><SectionHeading icon={<ClipboardCheck className="size-4" />} eyebrow="Client delivery" title="Approved evidence" />{distributedBriefings.map(briefing => <article key={briefing.id} className="rounded-[1.35rem] border border-[#e7ddba] bg-[#fffaf0] p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold">{briefing.title}</p><span className="rounded-full border border-[#e1cc8d] bg-white px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#805e2e]">Briefing</span></div><p className="mt-2 line-clamp-3 text-xs leading-5 text-[#6f6048]">{briefing.content.briefingSummary}</p><p className="mt-3 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#9b7843]">Distributed {briefing.distributedAt ? new Date(briefing.distributedAt).toLocaleDateString() : "internally"}</p></article>)}{delivery.data?.snapshots.length ? delivery.data.snapshots.map(snapshot => <article key={snapshot.id} className="rounded-[1.35rem] border border-[#d4e1d4] bg-[#f6fbf5] p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold">{snapshot.targetType.replace("_", " ")}</p><span className="rounded-full border border-[#bfd2be] bg-white px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.1em] text-[#396446]">{snapshot.outputFormat}</span></div><p className="mt-2 text-xs text-muted-foreground">Approved {new Date(snapshot.approvedAt).toLocaleDateString()}</p><p className="mt-3 font-mono text-[10px] text-[#69826e]">Evidence digest {snapshot.contentDigest.slice(0, 16)}…</p></article>) : !distributedBriefings.length ? <Empty icon={<LockKeyhole className="size-5" />} text="No client-delivery evidence snapshot or executive briefing has been distributed." /> : null}</div> : null}</section><footer className="fixed inset-x-0 bottom-0 mx-auto max-w-md border-t border-[#e4dfd4] bg-[#fffdf8]/95 px-5 py-3 backdrop-blur"><p className="text-center text-[10px] font-semibold uppercase tracking-[0.16em] text-[#8b978e]">Organization-private intelligence</p></footer></main>;
}

function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl bg-white/10 px-3 py-3"><p className="display-serif text-xl">{value}</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-[0.12em] text-[#b9c9be]">{label}</p></div>; }
function SectionHeading({ icon, eyebrow, title }: { icon: React.ReactNode; eyebrow: string; title: string }) { return <div className="flex items-center gap-2"><span className="text-[#9f733e]">{icon}</span><div><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-[#9f733e]">{eyebrow}</p><h2 className="mt-1 text-lg font-semibold">{title}</h2></div></div>; }
function Empty({ icon, text }: { icon: React.ReactNode; text: string }) { return <div className="rounded-[1.35rem] border border-dashed border-[#d7d2c4] px-5 py-10 text-center text-sm text-muted-foreground"><span className="mx-auto flex size-10 items-center justify-center rounded-2xl bg-[#fff5d8] text-[#9f733e]">{icon}</span><p className="mt-3">{text}</p></div>; }
