import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, ChevronRight, CircleAlert, Loader2, Search, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function NewResearch() {
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const catalog = trpc.marketIntel.catalog.useQuery();
  const tracked = trpc.marketIntel.tracked.useQuery();
  const [focusSlug, setFocusSlug] = useState("");
  const [projectName, setProjectName] = useState("");
  const [scope, setScope] = useState("");
  const trackedSlugs = useMemo(() => new Set(tracked.data?.map(industry => industry.industrySlug) ?? []), [tracked.data]);
  useEffect(() => { if (!focusSlug && catalog.data?.[0]) setFocusSlug(catalog.data[0].slug); }, [catalog.data, focusSlug]);
  const saveTracked = trpc.marketIntel.setTracked.useMutation({ onSuccess: () => utils.marketIntel.tracked.invalidate() });
  const createScan = trpc.marketIntel.createScan.useMutation({ onSuccess: ({ scanId }) => { toast.success("Your market scan is ready."); void utils.marketIntel.dashboard.invalidate(); setLocation(`/workspace/${scanId}`); }, onError: error => toast.error(error.message) });
  const focus = catalog.data?.find(industry => industry.slug === focusSlug);
  const isReady = Boolean(focusSlug && scope.trim().length >= 20 && !createScan.isPending);
  return <div className="mx-auto max-w-6xl space-y-7">
    <section className="enter-up"><p className="text-[11px] font-semibold uppercase tracking-[0.19em] text-[#9a713d]">New market scan</p><div className="mt-2 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="display-serif text-4xl leading-none md:text-5xl">Set the brief. Let the research move.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-muted-foreground">Choose the industry to analyze, keep the markets you follow close at hand, and frame the strategic question behind the engagement.</p></div><Badge variant="outline" className="w-fit border-[#d5c399] bg-[#f9f5e9] px-3 py-1.5 text-xs text-[#76572f]"><Sparkles className="mr-1.5 size-3.5" />Source-grounded analysis</Badge></div></section>
    <section className="grid gap-6 lg:grid-cols-[1.18fr_0.82fr]">
      <div className="paper-card rounded-[1.3rem] border bg-card p-5 md:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">01 / Industry selector</p><h2 className="display-serif mt-1 text-2xl">Focus market</h2></div><span className="text-xs text-muted-foreground">{trackedSlugs.size} tracked</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{catalog.isLoading ? <><div className="h-24 rounded-xl bg-muted animate-pulse" /><div className="h-24 rounded-xl bg-muted animate-pulse" /></> : catalog.data?.map(industry => { const isFocus = industry.slug === focusSlug; const isTracked = trackedSlugs.has(industry.slug); return <div key={industry.slug} className={`group relative rounded-xl border p-4 transition-all ${isFocus ? "border-[#2c6557] bg-[#edf3ec] shadow-sm" : "border-border bg-[#fcfbf7] hover:border-[#b8ad95]"}`}><button className="absolute inset-0 rounded-xl" aria-label={`Research ${industry.name}`} onClick={() => setFocusSlug(industry.slug)} /><div className="relative flex items-start justify-between gap-2 pointer-events-none"><span className={`flex size-7 items-center justify-center rounded-lg ${isFocus ? "bg-primary text-white" : "bg-[#eee9dc] text-[#6c776e]"}`}>{isFocus ? <Check className="size-4" /> : <Search className="size-3.5" />}</span><span className="rounded-full border border-[#d7c8a9] bg-[#fbf8ef] px-2 py-0.5 text-[10px] font-medium text-[#7f6239]">{isTracked ? "Tracked" : "Available"}</span></div><p className="relative mt-3 text-sm font-semibold">{industry.name}</p><p className="relative mt-1 text-xs leading-5 text-muted-foreground">{industry.description}</p><button onClick={(event) => { event.stopPropagation(); saveTracked.mutate({ slug: industry.slug, tracked: !isTracked }); }} disabled={saveTracked.isPending} className="relative mt-3 text-[11px] font-semibold text-primary hover:underline">{isTracked ? "Remove from watchlist" : "Track this industry"}</button></div>; })}</div></div>
      <aside className="rounded-[1.3rem] border border-[#d8c9a7] bg-[#f1ede0] p-5 md:p-7"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">What happens next</p><h2 className="display-serif mt-2 text-3xl leading-none">The research agent builds a usable first cut.</h2><div className="mt-6 space-y-5">{[["Current source scan", "Collects public reporting across competition, trends, regulation, and opportunity."],["Structured synthesis", "Distills the evidence into a market landscape and consultant perspective."],["Private workspace", "Saves sources, profiles, chat, notes, and exports to your account."]].map(([title, description], index) => <div key={title} className="flex gap-3"><span className="mt-0.5 flex size-6 shrink-0 items-center justify-center rounded-full border border-[#cbb995] text-[10px] font-bold text-[#7c5d34]">0{index + 1}</span><div><p className="text-sm font-semibold text-[#283c35]">{title}</p><p className="mt-1 text-xs leading-5 text-[#68756e]">{description}</p></div></div>)}</div><div className="mt-7 rounded-xl border border-[#d9ccaf] bg-[#faf7ef] p-3 text-xs leading-5 text-[#6c644e]"><CircleAlert className="mr-1 inline size-3.5 text-[#9b7444]" />Treat the scan as a research starting point. Source links remain visible for professional validation.</div></aside>
    </section>
    <section className="paper-card rounded-[1.3rem] border bg-card p-5 md:p-7"><div className="grid gap-6 lg:grid-cols-[0.85fr_1.55fr]"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">02 / Research direction</p><h2 className="display-serif mt-1 text-2xl">Give the scan a strategic lens.</h2><p className="mt-3 text-xs leading-5 text-muted-foreground">Be specific about the client question, geography, customer segment, investment case, or strategic decision behind the work.</p></div><div className="space-y-4"><div><Label htmlFor="project">Project or client label <span className="text-muted-foreground">(optional)</span></Label><Input id="project" value={projectName} onChange={event => setProjectName(event.target.value)} className="mt-2 bg-[#fdfcf8]" placeholder="e.g., Growth strategy engagement" /></div><div><Label htmlFor="scope">What should this scan resolve?</Label><Textarea id="scope" value={scope} onChange={event => setScope(event.target.value)} className="mt-2 min-h-32 bg-[#fdfcf8]" placeholder="e.g., Assess the competitive shape of the North American FinTech market, especially payments infrastructure and AI-enabled workflow opportunities for mid-market banks." /><div className="mt-2 flex justify-between text-[11px] text-muted-foreground"><span>{scope.trim().length < 20 ? "Add at least 20 characters to create the scan." : "Research direction is ready."}</span><span>{scope.length}/1,500</span></div></div><div className="flex flex-col items-start justify-between gap-3 border-t pt-5 sm:flex-row sm:items-center"><p className="text-xs text-muted-foreground">Focus: <strong className="text-foreground">{focus?.name || "Select an industry"}</strong></p><Button disabled={!isReady} onClick={() => createScan.mutate({ industrySlug: focusSlug, scope: scope.trim(), projectName: projectName.trim() || undefined })} className="rounded-xl bg-primary px-5 py-5 text-primary-foreground hover:bg-primary/90">{createScan.isPending ? <><Loader2 className="mr-2 size-4 animate-spin" />Scanning public sources…</> : <>Start market scan <ChevronRight className="ml-1.5 size-4" /></>}</Button></div></div></div></section>
  </div>;
}
