import { AIChatBox, type Message } from "@/components/AIChatBox";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { exportMarketScanPdf, exportMarketScanPptx, type MarketScanReport } from "@/lib/reportExport";
import { AlertTriangle, ArrowLeft, BookOpen, Bot, Download, FileText, FileDown, LayoutPanelTop, Loader2, MessageSquareText, Network, NotebookPen, Presentation, Target } from "lucide-react";
import { type ComponentType, useMemo, useState } from "react";
import { toast } from "sonner";
import { Streamdown } from "streamdown";
import { useLocation, useRoute } from "wouter";

type Analysis = { executiveSummary: string; keyPlayers: { name: string; segment: string; positioning: string; strategicSignal: string; sourceIds: string[] }[]; trends: { title: string; detail: string; timeHorizon: string; strategicImplication: string; sourceIds: string[] }[]; risks: { title: string; detail: string; likelihood: string; impact: string; sourceIds: string[] }[]; opportunities: { title: string; detail: string; priority: string; sourceIds: string[] }[]; landscape: { marketDefinition: string; segments: { name: string; description: string; examples: string[] }[]; incumbentPositioning: string; challengerPositioning: string; marketSizeSignals: { signal: string; context: string; sourceIds: string[] }[] }; executiveBrief: { headline: string; narrative: string; imperatives: string[]; clientQuestions: string[] } };
type Source = { id: string; title: string; publisher: string; publishedAt: string; url: string; excerpt: string };
const tabs = [{ id: "scan", label: "Market scan", icon: Target }, { id: "landscape", label: "Landscape", icon: LayoutPanelTop }, { id: "competitors", label: "Competitors", icon: Network }, { id: "brief", label: "Industry perspective", icon: FileText }, { id: "notes", label: "Notes", icon: NotebookPen }];
const parse = <T,>(value: string): T | null => { try { return JSON.parse(value) as T; } catch { return null; } };
const download = (filename: string, content: string) => { const url = URL.createObjectURL(new Blob([content], { type: "text/markdown;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); };
const sourceLabels = (ids: string[]) => ids.map(id => <span key={id} className="rounded bg-[#f1e8d2] px-1.5 py-0.5 text-[10px] font-semibold text-[#76572f]">{id}</span>);

export default function ScanDetail() {
  const [, params] = useRoute("/workspace/:scanId"); const scanId = params?.scanId ?? ""; const [, setLocation] = useLocation(); const utils = trpc.useUtils(); const [tab, setTab] = useState("scan"); const [noteTitle, setNoteTitle] = useState(""); const [noteContent, setNoteContent] = useState(""); const [selectedCompetitor, setSelectedCompetitor] = useState(""); const [exporting, setExporting] = useState<"pdf" | "pptx" | null>(null);
  const query = trpc.marketIntel.scan.useQuery({ scanId }, { enabled: Boolean(scanId) }); const data = query.data; const analysis = useMemo(() => data ? parse<Analysis>(data.scan.analysisJson) : null, [data]); const sources = useMemo(() => data ? parse<Source[]>(data.scan.sourceJson) ?? [] : [], [data]);
  const ask = trpc.marketIntel.ask.useMutation({ onSuccess: () => utils.marketIntel.scan.invalidate({ scanId }), onError: error => toast.error(error.message) }); const addNote = trpc.marketIntel.addNote.useMutation({ onSuccess: () => { setNoteTitle(""); setNoteContent(""); void utils.marketIntel.scan.invalidate({ scanId }); toast.success("Note saved to this research workspace."); }, onError: error => toast.error(error.message) });
  const messages: Message[] = data?.messages.map(message => ({ role: message.role, content: message.content })) ?? [];
  if (query.isLoading) return <div className="space-y-5"><Skeleton className="h-11 w-40" /><Skeleton className="h-48 rounded-3xl" /><Skeleton className="h-80 rounded-3xl" /></div>;
  if (!data || !analysis) return <div className="rounded-3xl border bg-card p-10 text-center"><p className="display-serif text-3xl">Research record unavailable.</p><Button variant="outline" onClick={() => setLocation("/workspace")} className="mt-5">Return to workspace</Button></div>;
  const activeTab = tabs.find(item => item.id === tab);
  const report: MarketScanReport = { industryName: data.scan.industryName, projectName: data.scan.projectName, scope: data.scan.scope, createdAt: data.scan.createdAt, analysis, sources, competitors: data.profiles };
  const runExport = async (format: "pdf" | "pptx") => { setExporting(format); try { if (format === "pdf") await exportMarketScanPdf(report); else await exportMarketScanPptx(report); toast.success(`${format === "pdf" ? "PDF" : "PowerPoint"} report prepared for download.`); } catch (error) { toast.error(error instanceof Error ? error.message : "The report could not be exported."); } finally { setExporting(null); } };
  return <div className="mx-auto max-w-7xl space-y-5"><button onClick={() => setLocation("/workspace")} className="flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-primary"><ArrowLeft className="size-3.5" />Workspace</button><section className="overflow-hidden rounded-[1.45rem] border border-[#d7ccb5] bg-[#f1eee4] p-6 md:p-8"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-4 flex flex-wrap gap-2"><Badge variant="outline" className="border-[#d7c89f] bg-[#fcf8eb] text-[#76572f]">{data.scan.industryName}</Badge>{data.scan.projectName ? <Badge variant="outline" className="border-[#c4d0c4] bg-[#f4f8f3] text-[#42604e]">{data.scan.projectName}</Badge> : null}</div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[#99703c]">Market intelligence record</p><h1 className="display-serif mt-2 max-w-4xl text-4xl leading-[0.95] text-[#1c342d] md:text-5xl">{analysis.executiveBrief.headline}</h1></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={Boolean(exporting)} onClick={() => void runExport("pdf")} className="rounded-xl bg-[#fbfaf5]">{exporting === "pdf" ? <Loader2 className="mr-2 size-4 animate-spin" /> : <FileDown className="mr-2 size-4" />}Export PDF</Button><Button variant="outline" disabled={Boolean(exporting)} onClick={() => void runExport("pptx")} className="rounded-xl bg-[#fbfaf5]">{exporting === "pptx" ? <Loader2 className="mr-2 size-4 animate-spin" /> : <Presentation className="mr-2 size-4" />}Export PowerPoint</Button><Button variant="outline" onClick={async () => { const result = await utils.marketIntel.exportBrief.fetch({ scanId }); download(result.filename, result.content); }} className="rounded-xl bg-[#fbfaf5]"><Download className="mr-2 size-4" />Markdown</Button><Button onClick={() => setTab("brief")} className="rounded-xl bg-primary text-primary-foreground hover:bg-primary/90"><BookOpen className="mr-2 size-4" />Read perspective</Button></div></div><p className="mt-5 max-w-4xl text-sm leading-6 text-[#53645b]">{data.scan.scope}</p></section>
    <div className="flex gap-1 overflow-x-auto border-b border-border pb-px">{tabs.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={cn("flex shrink-0 items-center gap-2 border-b-2 px-3 py-3 text-xs font-semibold transition-colors", tab === item.id ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground")}><item.icon className="size-3.5" />{item.label}</button>)}</div>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="min-w-0">{tab === "scan" && <ScanView analysis={analysis} />} {tab === "landscape" && <LandscapeView analysis={analysis} />} {tab === "competitors" && <CompetitorView profiles={data.profiles} selected={selectedCompetitor} setSelected={setSelectedCompetitor} onExport={async name => { const result = await utils.marketIntel.exportCompetitor.fetch({ scanId, competitorName: name }); download(result.filename, result.content); }} />} {tab === "brief" && <BriefView analysis={analysis} onExport={async () => { const result = await utils.marketIntel.exportBrief.fetch({ scanId }); download(result.filename, result.content); }} />} {tab === "notes" && <NotesView notes={data.notes} title={noteTitle} content={noteContent} setTitle={setNoteTitle} setContent={setNoteContent} save={() => addNote.mutate({ scanId, title: noteTitle, content: noteContent })} saving={addNote.isPending} />}</div><aside className="space-y-5"><div className="paper-card rounded-[1.25rem] border bg-card p-4"><div className="mb-3 flex items-center gap-2"><Bot className="size-4 text-[#a37842]" /><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#81633d]">Ask the research agent</p></div><AIChatBox messages={messages} onSendMessage={question => ask.mutate({ scanId, question })} isLoading={ask.isPending} height="430px" placeholder="Ask about this market scan…" emptyStateMessage="Ask a strategic follow-up based on this scan." suggestedPrompts={["Which opportunity deserves the first client discussion?", "Where is the most credible disruption risk?", "Compare the incumbent and challenger positions."]} className="rounded-xl border-[#e0d8c7] shadow-none" /></div><div className="paper-card rounded-[1.25rem] border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Research sources</p><div className="mt-4 space-y-3">{sources.slice(0, 5).map(source => <a key={source.id} href={source.url} target="_blank" rel="noreferrer" className="block rounded-lg border border-transparent p-2 transition-colors hover:border-[#d9caa9] hover:bg-[#fcfaf4]"><div className="flex gap-2"><span className="mt-0.5 shrink-0 text-[10px] font-bold text-[#9b7542]">{source.id}</span><p className="line-clamp-2 text-xs font-semibold leading-4">{source.title}</p></div><p className="mt-1 pl-5 text-[10px] text-muted-foreground">{source.publisher}</p></a>)}</div></div></aside></section></div>;
}

function ScanView({ analysis }: { analysis: Analysis }) { return <div className="space-y-5"><article className="paper-card rounded-[1.25rem] border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Executive synthesis</p><p className="display-serif mt-3 text-2xl leading-snug">{analysis.executiveSummary}</p></article><div className="grid gap-5 lg:grid-cols-2"><SignalList title="Key players" icon={Network} items={analysis.keyPlayers.map(player => ({ title: player.name, detail: `${player.segment} — ${player.positioning} ${player.strategicSignal}`, sources: player.sourceIds }))} /><SignalList title="Emerging trends" icon={Target} items={analysis.trends.map(trend => ({ title: trend.title, detail: `${trend.detail} Strategic implication: ${trend.strategicImplication}`, sources: trend.sourceIds }))} /><SignalList title="Risks to monitor" icon={AlertTriangle} tone="risk" items={analysis.risks.map(risk => ({ title: risk.title, detail: `${risk.detail} Likelihood: ${risk.likelihood}; impact: ${risk.impact}.`, sources: risk.sourceIds }))} /><SignalList title="Strategic opportunities" icon={SparkleIcon} tone="opportunity" items={analysis.opportunities.map(opportunity => ({ title: opportunity.title, detail: `${opportunity.detail} Priority: ${opportunity.priority}.`, sources: opportunity.sourceIds }))} /></div></div>; }
function SignalList({ title, icon: Icon, items, tone = "default" }: { title: string; icon: ComponentType<{ className?: string }>; items: { title: string; detail: string; sources: string[] }[]; tone?: "default" | "risk" | "opportunity" }) { const colors = tone === "risk" ? "bg-[#f9ede8] text-[#a24f39]" : tone === "opportunity" ? "bg-[#ebf3ea] text-[#337054]" : "bg-[#eef0e9] text-primary"; return <article className="paper-card rounded-[1.25rem] border bg-card p-5"><div className="flex items-center gap-2"><span className={`flex size-7 items-center justify-center rounded-lg ${colors}`}><Icon className="size-3.5" /></span><h2 className="display-serif text-xl">{title}</h2></div><div className="mt-4 space-y-4">{items.length ? items.map((item, index) => <div key={`${item.title}-${index}`} className="border-l border-[#ddd3bd] pl-3"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{item.title}</p>{sourceLabels(item.sources)}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.detail}</p></div>) : <p className="text-xs text-muted-foreground">No structured signals were saved.</p>}</div></article>; }
function SparkleIcon({ className }: { className?: string }) { return <MessageSquareText className={className} />; }
function LandscapeView({ analysis }: { analysis: Analysis }) { return <div className="space-y-5"><article className="paper-card rounded-[1.25rem] border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Market definition</p><p className="display-serif mt-3 text-2xl leading-snug">{analysis.landscape.marketDefinition}</p></article><article className="paper-card rounded-[1.25rem] border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Market architecture</p><div className="mt-5 grid gap-4 md:grid-cols-2">{analysis.landscape.segments.map(segment => <div key={segment.name} className="rounded-xl border bg-[#fcfbf7] p-4"><h2 className="text-sm font-semibold">{segment.name}</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">{segment.description}</p><p className="mt-3 text-[11px] font-medium text-[#7c603a]">Examples: {segment.examples.join(", ")}</p></div>)}</div></article><div className="grid gap-5 md:grid-cols-2"><article className="rounded-[1.25rem] border bg-[#eaf2ea] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#4b705a]">Incumbent position</p><p className="display-serif mt-3 text-xl leading-snug">{analysis.landscape.incumbentPositioning}</p></article><article className="rounded-[1.25rem] border bg-[#f5efe4] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#89683d]">Challenger position</p><p className="display-serif mt-3 text-xl leading-snug">{analysis.landscape.challengerPositioning}</p></article></div><article className="paper-card rounded-[1.25rem] border bg-card p-6"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Market-size signals</p><div className="mt-4 divide-y">{analysis.landscape.marketSizeSignals.map((signal, index) => <div key={index} className="py-4 first:pt-0"><div className="flex flex-wrap gap-2"><p className="text-sm font-semibold">{signal.signal}</p>{sourceLabels(signal.sourceIds)}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">{signal.context}</p></div>)}</div></article></div>; }
function CompetitorView({ profiles, selected, setSelected, onExport }: { profiles: { id: string; name: string; segment: string; businessModel: string; positioning: string; strengthsJson: string; weaknessesJson: string; recentMovesJson: string; strategicSignalsJson: string }[]; selected: string; setSelected: (name: string) => void; onExport: (name: string) => void }) { const active = profiles.find(profile => profile.name === selected) || profiles[0]; const list = (value: string) => parse<string[]>(value) ?? []; return <div className="grid gap-5 lg:grid-cols-[220px_1fr]"> <nav className="paper-card h-fit rounded-[1.25rem] border bg-card p-3">{profiles.map(profile => <button key={profile.id} onClick={() => setSelected(profile.name)} className={cn("w-full rounded-xl px-3 py-3 text-left", (active?.id === profile.id) ? "bg-[#edf3ec]" : "hover:bg-muted")}><p className="text-sm font-semibold">{profile.name}</p><p className="mt-1 text-[11px] text-muted-foreground">{profile.segment}</p></button>)}</nav>{active ? <article className="paper-card rounded-[1.25rem] border bg-card p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Competitor profile</p><h2 className="display-serif mt-2 text-3xl">{active.name}</h2><Badge variant="outline" className="mt-3 border-[#d7c89f] bg-[#fdf9ee] text-[#76572f]">{active.segment}</Badge></div><Button variant="outline" onClick={() => onExport(active.name)} className="h-fit rounded-xl"><Download className="mr-2 size-4" />Export profile</Button></div><div className="mt-6 grid gap-5 md:grid-cols-2"><ProfileBlock title="Business model" content={active.businessModel} /><ProfileBlock title="Positioning" content={active.positioning} /><ProfileBlock title="Strengths" bullets={list(active.strengthsJson)} /><ProfileBlock title="Weaknesses / watchouts" bullets={list(active.weaknessesJson)} /><ProfileBlock title="Recent moves" bullets={list(active.recentMovesJson)} /><ProfileBlock title="Strategic signals" bullets={list(active.strategicSignalsJson)} /></div></article> : <div className="rounded-[1.25rem] border border-dashed p-10 text-center text-sm text-muted-foreground">No competitor profiles were generated for this scan.</div>}</div>; }
function ProfileBlock({ title, content, bullets }: { title: string; content?: string; bullets?: string[] }) { return <section className="rounded-xl border bg-[#fcfbf7] p-4"><p className="text-xs font-semibold uppercase tracking-[0.13em] text-[#927044]">{title}</p>{content ? <p className="mt-3 text-sm leading-6 text-[#485a50]">{content}</p> : <ul className="mt-3 space-y-2">{bullets?.map((bullet, index) => <li key={index} className="flex gap-2 text-xs leading-5 text-[#485a50]"><span className="mt-2 size-1 shrink-0 rounded-full bg-[#a37842]" />{bullet}</li>)}</ul>}</section>; }
function BriefView({ analysis, onExport }: { analysis: Analysis; onExport: () => void }) { return <article className="paper-card rounded-[1.25rem] border bg-card p-6 md:p-8"><div className="flex flex-col gap-4 border-b pb-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Industry perspective</p><h2 className="display-serif mt-2 text-3xl leading-none md:text-4xl">{analysis.executiveBrief.headline}</h2></div><Button variant="outline" onClick={onExport} className="rounded-xl"><Download className="mr-2 size-4" />Markdown</Button></div><div className="prose prose-sm mt-7 max-w-none prose-headings:font-serif prose-p:leading-7 prose-p:text-[#485a50]"><Streamdown>{analysis.executiveBrief.narrative}</Streamdown><h3>Consultant imperatives</h3><ul>{analysis.executiveBrief.imperatives.map((item, index) => <li key={index}>{item}</li>)}</ul><h3>Questions to resolve with the client</h3><ul>{analysis.executiveBrief.clientQuestions.map((item, index) => <li key={index}>{item}</li>)}</ul></div></article>; }
function NotesView({ notes, title, content, setTitle, setContent, save, saving }: { notes: { id: string; title: string; content: string; createdAt: Date | string }[]; title: string; content: string; setTitle: (value: string) => void; setContent: (value: string) => void; save: () => void; saving: boolean }) { return <div className="grid gap-5 lg:grid-cols-[0.78fr_1.22fr]"><article className="paper-card rounded-[1.25rem] border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Saved notes</p><div className="mt-4 space-y-3">{notes.length ? notes.map(note => <div key={note.id} className="rounded-xl border bg-[#fcfbf7] p-3"><p className="text-sm font-semibold">{note.title}</p><p className="mt-1 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">{note.content}</p></div>) : <p className="text-xs leading-5 text-muted-foreground">No annotations yet. Capture a thought while the evidence is in view.</p>}</div></article><article className="paper-card rounded-[1.25rem] border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">New annotation</p><div className="mt-4 space-y-4"><div><Label htmlFor="note-title">Note title</Label><Input id="note-title" value={title} onChange={event => setTitle(event.target.value)} className="mt-2" placeholder="e.g., Open questions for client team" /></div><div><Label htmlFor="note-content">Observation</Label><Textarea id="note-content" value={content} onChange={event => setContent(event.target.value)} className="mt-2 min-h-40" placeholder="Capture your interpretation, caveat, or next question…" /></div><Button disabled={!title.trim() || !content.trim() || saving} onClick={save} className="rounded-xl bg-primary text-primary-foreground hover:bg-primary/90">{saving ? <Loader2 className="mr-2 size-4 animate-spin" /> : <NotebookPen className="mr-2 size-4" />}Save note</Button></div></article></div>; }
