import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { analyzeSourceIntelligence, type IntelligenceSource } from "@/lib/sourceIntelligence";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, ExternalLink, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

const parse = <T,>(value: string): T | null => { try { return JSON.parse(value) as T; } catch { return null; } };
const scoreTone = (score: number) => score >= 75 ? "text-[#3d7350]" : score >= 55 ? "text-[#8a6829]" : "text-[#a24f39]";
const tierTone = { authoritative: "border-[#bdd3c0] bg-[#eff7ef] text-[#426a4c]", established: "border-[#bed2dd] bg-[#eef7fa] text-[#3f6879]", specialist: "border-[#e3c993] bg-[#fff8e8] text-[#876323]", unverified: "border-border bg-muted text-muted-foreground" };

export default function SourceIntelligence() {
  const [, setLocation] = useLocation();
  const workspace = trpc.marketIntel.workspace.useQuery();
  const [scanId, setScanId] = useState("");
  useEffect(() => { if (!scanId && workspace.data?.scans[0]) setScanId(workspace.data.scans[0].id); }, [scanId, workspace.data]);
  const scan = trpc.marketIntel.scan.useQuery({ scanId }, { enabled: Boolean(scanId) });
  const sources = useMemo(() => scan.data ? parse<IntelligenceSource[]>(scan.data.scan.sourceJson) ?? [] : [], [scan.data]);
  const summary = useMemo(() => analyzeSourceIntelligence(sources, scan.data ? new Date(scan.data.scan.createdAt) : new Date()), [scan.data, sources]);

  return <div className="mx-auto max-w-7xl space-y-7"><section className="enter-up overflow-hidden rounded-[1.5rem] border border-[#d9d1be] bg-[#f1eee4] px-6 py-7 md:px-9 md:py-9"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="max-w-3xl"><p className="text-[11px] font-semibold uppercase tracking-[0.19em] text-[#99703c]">Evidence governance</p><h1 className="display-serif mt-2 text-4xl leading-[0.94] text-[#1c342d] md:text-5xl">Know the strength of the research beneath the point of view.</h1><p className="mt-5 text-sm leading-6 text-[#52635b]">Review deterministic authority, recency, diversity, and traceability signals for each public-source scan. These are evidence-quality indicators, not assertions that individual claims are true.</p></div><div className="rounded-2xl border border-[#d7c8a7] bg-[#fbf8ef] px-4 py-3"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-[#8a6c41]">Evidence confidence</p><p className={`display-serif mt-1 text-3xl leading-none ${scoreTone(summary.score)}`}>{summary.score || "—"}<span className="ml-1 text-sm">/100</span></p></div></div></section>
    <section className="grid gap-6 xl:grid-cols-[0.72fr_1.28fr]"><aside className="paper-card rounded-[1.3rem] border bg-card p-5"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#947044]">Research records</p><h2 className="display-serif mt-1 text-2xl">Select a scan</h2><div className="mt-5 space-y-2">{workspace.isLoading ? <><Skeleton className="h-16 rounded-xl" /><Skeleton className="h-16 rounded-xl" /></> : workspace.data?.scans.length ? workspace.data.scans.map(item => <button key={item.id} onClick={() => setScanId(item.id)} className={`w-full rounded-xl border p-3 text-left transition-colors ${item.id === scanId ? "border-[#2c6557] bg-[#edf3ec]" : "border-transparent bg-[#fcfbf7] hover:border-[#d9caa9]"}`}><p className="text-sm font-semibold">{item.industryName}</p><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-muted-foreground">{item.executiveSummary}</p></button>) : <p className="rounded-xl border border-dashed p-5 text-xs leading-5 text-muted-foreground">Create a market scan to begin reviewing its source governance.</p>}</div></aside>
      <div>{scan.isLoading ? <div className="grid gap-4"><Skeleton className="h-36 rounded-[1.3rem]" /><Skeleton className="h-80 rounded-[1.3rem]" /></div> : scan.data ? <div className="space-y-5"><article className="paper-card rounded-[1.3rem] border bg-card p-5 md:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap gap-2"><Badge variant="outline" className="border-[#d7c89f] bg-[#fcf8eb] text-[#76572f]">{scan.data.scan.industryName}</Badge><Badge variant="outline" className={summary.confidence === "high" ? tierTone.authoritative : summary.confidence === "moderate" ? tierTone.specialist : tierTone.unverified}>{summary.confidence} confidence</Badge></div><h2 className="display-serif mt-4 text-3xl">Evidence quality summary</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{summary.governanceNote}</p></div><Button variant="outline" onClick={() => setLocation(`/workspace/${scan.data.scan.id}`)} className="rounded-xl"><ArrowRight className="mr-2 size-4" />Open scan</Button></div><div className="mt-6 grid gap-3 sm:grid-cols-4">{[["Sources", summary.totalSources], ["Publishers", summary.uniquePublishers], ["Current", summary.currentSources], ["Linked", summary.traceableSources]].map(([label, value]) => <div key={String(label)} className="rounded-xl border bg-[#fcfbf7] p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-[#927044]">{label}</p><p className="display-serif mt-2 text-3xl">{value}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2">{Object.entries(summary.tierCounts).map(([tier, count]) => <Badge key={tier} variant="outline" className={tierTone[tier as keyof typeof tierTone]}>{count} {tier}</Badge>)}</div></article>
        <article className="paper-card rounded-[1.3rem] border bg-card p-5 md:p-7"><div className="flex items-center gap-2"><span className="flex size-8 items-center justify-center rounded-xl bg-[#edf3ec] text-[#3d7350]"><ShieldCheck className="size-4" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[#4b705a]">Source register</p><h2 className="display-serif mt-1 text-2xl">Authority and recency review</h2></div></div><div className="mt-5 divide-y divide-border">{summary.quality.map(source => <div key={source.id} className="py-4 first:pt-0"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-bold text-[#9b7542]">{source.id}</span><a href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-semibold hover:text-primary hover:underline">{source.title}<ExternalLink className="size-3" /></a><Badge variant="outline" className={tierTone[source.tier]}>{source.tier}</Badge>{source.recency === "current" ? <span className="flex items-center gap-1 text-[10px] font-semibold text-[#426a4c]"><CheckCircle2 className="size-3" />Current</span> : <span className="text-[10px] font-medium text-muted-foreground">{source.recency === "aging" ? `${source.daysOld} days old` : "Undated"}</span>}</div><p className="mt-1 text-xs text-muted-foreground">{source.publisher || "Publisher not supplied"} · Authority signal {source.authorityScore}/100</p><p className="mt-2 max-w-3xl text-xs leading-5 text-muted-foreground">{source.rationale}</p></div></div></div>)}</div>{summary.totalSources === 0 ? <div className="rounded-xl border border-dashed p-7 text-center text-xs leading-5 text-muted-foreground"><Sparkles className="mx-auto mb-3 size-4 text-[#9b7542]" />This saved scan does not contain a source packet that can be assessed.</div> : null}</article></div> : <div className="rounded-[1.3rem] border border-dashed p-10 text-center text-sm text-muted-foreground">Choose a saved scan to review its source intelligence.</div>}</div></section></div>;
}
