import { beforeEach, describe, expect, it, vi } from "vitest";
import type { TrpcContext } from "../_core/context";

const mocks = vi.hoisted(() => ({ active: vi.fn(), operations: vi.fn(), createMandate: vi.fn(), createWatchlist: vi.fn(), updateWatchlist: vi.fn(), updatePolicy: vi.fn(), audit: vi.fn() }));
vi.mock("./db", () => ({ addChatTurn: vi.fn(), addNote: vi.fn(), dashboard: vi.fn(), getScan: vi.fn(), listTrackedIndustries: vi.fn(), listWorkspace: vi.fn(), saveScanPackage: vi.fn(), setTrackedIndustry: vi.fn() }));
vi.mock("./research", () => ({ answerResearchQuestion: vi.fn(), collectPublicSources: vi.fn(), generateMarketScan: vi.fn() }));
vi.mock("./knowledge", () => ({ createKnowledgeAsset: vi.fn(), createKnowledgeCollection: vi.fn(), listKnowledge: vi.fn(), listPortfolioViews: vi.fn(), portfolioSnapshot: vi.fn(), savePortfolioView: vi.fn(), searchKnowledge: vi.fn(), updateKnowledgeAssetTags: vi.fn() }));
vi.mock("./monitoring", () => ({ createMonitoredIndustry: vi.fn(), deleteMonitoredIndustry: vi.fn(), getMonitoringPreferences: vi.fn(), listAlerts: vi.fn(), listMonitoredIndustries: vi.fn(), markAlertRead: vi.fn(), runMonitoredScan: vi.fn(), unreadAlertCount: vi.fn(), updateMonitoredIndustry: vi.fn(), updateMonitoringPreferences: vi.fn() }));
vi.mock("./organization", () => ({ getActiveOrganization: mocks.active, addExistingMember: vi.fn(), switchOrganization: vi.fn(), canCreateResearch: vi.fn((role: string) => role !== "viewer"), canManageMembers: vi.fn((role: string) => role === "owner" || role === "admin"), changeMemberRole: vi.fn(), listMembers: vi.fn(), listOrganizations: vi.fn() }));
vi.mock("./governance", () => ({ getGovernanceOverview: vi.fn(), recordAuditEvent: mocks.audit, updateRetentionPolicy: vi.fn() }));
vi.mock("./collaboration", () => ({ createComment: vi.fn(), decideReview: vi.fn(), getCollaborationOverview: vi.fn(), listNotifications: vi.fn(), markNotificationRead: vi.fn(), requestReview: vi.fn() }));
vi.mock("./orchestration", () => ({ listAgentRuns: vi.fn(), runEvidenceOrchestration: vi.fn() }));
vi.mock("./portfolioOperations", () => ({ listPortfolioOperations: mocks.operations, createMandate: mocks.createMandate, createWatchlist: mocks.createWatchlist, updateMandateStatus: vi.fn(), updatePortfolioPolicy: mocks.updatePolicy, updateWatchlistStatus: mocks.updateWatchlist }));

import { marketIntelRouter } from "./router";

const context = (): TrpcContext => ({ user: { id: 12, openId: "portfolio-user", name: "Portfolio user", email: "portfolio@example.com", loginMethod: "manus", role: "user", createdAt: new Date(), updatedAt: new Date(), lastSignedIn: new Date() }, req: { headers: {} } as TrpcContext["req"], res: {} as TrpcContext["res"] });
const activeFor = (role: "owner" | "admin" | "research_lead" | "analyst" | "viewer") => ({ organization: { id: "org-portfolio", name: "Portfolio team", ownerUserId: 1 }, membership: { organizationId: "org-portfolio", userId: 12, role } });
const mandateInput = { ownerUserId: 12, name: "FinTech strategy", clientLabel: "Priority account", description: "Assess portfolio exposure and decision options.", status: "scoping" as const, priority: "standard" as const, targetDate: null, scanIds: [], knowledgeAssetIds: [] };

describe("marketIntel portfolio operation controls", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.active.mockResolvedValue(activeFor("analyst")); mocks.operations.mockResolvedValue({ mandates: [], watchlists: [], policy: {}, metrics: {} }); mocks.createMandate.mockResolvedValue({ id: "mandate-1" }); mocks.createWatchlist.mockResolvedValue({ id: "watch-1" }); mocks.updateWatchlist.mockResolvedValue({ id: "watch-1", status: "escalated" }); mocks.updatePolicy.mockResolvedValue({ id: "policy-1" }); });
  it("retrieves portfolio operations within only the active organization", async () => { await marketIntelRouter.createCaller(context()).portfolio.operations(); expect(mocks.operations).toHaveBeenCalledWith("org-portfolio", 12); });
  it("blocks viewer mandate creation and non-admin policy updates", async () => { mocks.active.mockResolvedValue(activeFor("viewer")); await expect(marketIntelRouter.createCaller(context()).portfolio.createMandate(mandateInput)).rejects.toMatchObject({ code: "FORBIDDEN" }); await expect(marketIntelRouter.createCaller(context()).portfolio.updatePolicy({ maxActiveMandates: 12, requireMandateOwner: true, requireReviewForCritical: true })).rejects.toMatchObject({ code: "FORBIDDEN" }); expect(mocks.createMandate).not.toHaveBeenCalled(); expect(mocks.updatePolicy).not.toHaveBeenCalled(); });
  it("persists a contributor mandate and records the private audit event", async () => { await marketIntelRouter.createCaller(context()).portfolio.createMandate(mandateInput); expect(mocks.createMandate).toHaveBeenCalledWith(expect.objectContaining({ organizationId: "org-portfolio", createdByUserId: 12, name: "FinTech strategy" })); expect(mocks.audit).toHaveBeenCalledWith("org-portfolio", 12, expect.objectContaining({ eventType: "portfolio.mandate.created", resourceId: "mandate-1", metadata: expect.objectContaining({ priority: "standard" }) })); });
  it("allows an administrator to update only its active organization policy and audits the change", async () => { mocks.active.mockResolvedValue(activeFor("admin")); await marketIntelRouter.createCaller(context()).portfolio.updatePolicy({ maxActiveMandates: 12, requireMandateOwner: false, requireReviewForCritical: true }); expect(mocks.updatePolicy).toHaveBeenCalledWith({ organizationId: "org-portfolio", updatedByUserId: 12, maxActiveMandates: 12, requireMandateOwner: false, requireReviewForCritical: true }); expect(mocks.audit).toHaveBeenCalledWith("org-portfolio", 12, expect.objectContaining({ eventType: "organization.portfolio_policy.updated", resourceId: "policy-1" })); });
  it("enforces contributor access and audits private watchlist creation and escalation", async () => { mocks.active.mockResolvedValue(activeFor("viewer")); await expect(marketIntelRouter.createCaller(context()).portfolio.createWatchlist({ ownerUserId: 12, mandateId: null, targetType: "risk_theme", label: "Funding risk", rationale: "Track the evidence.", status: "watching" })).rejects.toMatchObject({ code: "FORBIDDEN" }); mocks.active.mockResolvedValue(activeFor("analyst")); await marketIntelRouter.createCaller(context()).portfolio.createWatchlist({ ownerUserId: 12, mandateId: null, targetType: "risk_theme", label: "Funding risk", rationale: "Track the evidence.", status: "watching" }); await marketIntelRouter.createCaller(context()).portfolio.updateWatchlistStatus({ watchlistId: "watch-1", status: "escalated" }); expect(mocks.createWatchlist).toHaveBeenCalledWith(expect.objectContaining({ organizationId: "org-portfolio", createdByUserId: 12, label: "Funding risk" })); expect(mocks.audit).toHaveBeenCalledWith("org-portfolio", 12, expect.objectContaining({ eventType: "portfolio.watchlist.created", resourceId: "watch-1" })); expect(mocks.audit).toHaveBeenCalledWith("org-portfolio", 12, expect.objectContaining({ eventType: "portfolio.watchlist.status_updated", resourceId: "watch-1", metadata: { status: "escalated" } })); });
});
