import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { parse as parseCookie } from "cookie";
import { COOKIE_NAME } from "@shared/const";
import { protectedProcedure, router } from "../_core/trpc";
import { channelForQuestionMode, selectConversationHistory } from "./chat";
import { INDUSTRY_CATALOG, getIndustry } from "./catalog";
import { addChatTurn, addNote, dashboard, getScan, listTrackedIndustries, listWorkspace, saveScanPackage, setTrackedIndustry } from "./db";
import { renderBriefMarkdown, renderCompetitorMarkdown, renderRiskAnswerMarkdown } from "./markdown";
import { createMonitoredIndustry, deleteMonitoredIndustry, getMonitoringPreferences, listAlerts, listMonitoredIndustries, markAlertRead, runMonitoredScan, unreadAlertCount, updateMonitoredIndustry, updateMonitoringPreferences } from "./monitoring";
import { createKnowledgeAsset, createKnowledgeCollection, listKnowledge, listPortfolioViews, portfolioSnapshot, savePortfolioView, searchKnowledge, updateKnowledgeAssetTags } from "./knowledge";
import { getGovernanceOverview, recordAuditEvent, updateRetentionPolicy } from "./governance";
import { addExistingMember, canCreateResearch, canManageMembers, changeMemberRole, getActiveOrganization, listMembers, listOrganizations, switchOrganization, type OrganizationRole } from "./organization";
import { answerResearchQuestion, collectPublicSources, generateMarketScan, type ResearchSource, type ScanAnalysis } from "./research";

const idInput = z.object({ scanId: z.string().min(1).max(40) });
const memberRole = z.enum(["admin", "research_lead", "analyst", "viewer"]);
const parseStoredScan = (sourceJson: string, analysisJson: string) => ({ sources: JSON.parse(sourceJson) as ResearchSource[], analysis: JSON.parse(analysisJson) as ScanAnalysis });
const active = (user: { id: number; name?: string | null }) => getActiveOrganization(user.id, user.name);
const researchAllowed = (role: OrganizationRole) => { if (!canCreateResearch(role)) throw new TRPCError({ code: "FORBIDDEN", message: "Your organization role is view-only." }); };
const memberManagementAllowed = (role: OrganizationRole) => { if (!canManageMembers(role)) throw new TRPCError({ code: "FORBIDDEN", message: "Only organization owners and admins can manage members." }); };
const governanceAllowed = memberManagementAllowed;
const sessionFromRequest = (request: { headers: { cookie?: string; authorization?: string } }) => {
  const cookieValue = parseCookie(request.headers.cookie ?? "")[COOKIE_NAME];
  if (cookieValue) return cookieValue;
  const authorization = request.headers.authorization;
  return authorization?.startsWith("Bearer ") ? authorization.slice(7) : "";
};

export const marketIntelRouter = router({
  organization: router({
    summary: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); const organizations = await listOrganizations(ctx.user.id, ctx.user.name); const members = await listMembers(current.organization.id); return { active: { ...current.organization, role: current.membership.role }, organizations: organizations.organizations, members }; }),
    switch: protectedProcedure.input(z.object({ organizationId: z.string().min(1).max(40) })).mutation(({ ctx, input }) => switchOrganization(ctx.user.id, input.organizationId)),
    addMember: protectedProcedure.input(z.object({ email: z.string().email().max(320), role: memberRole })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); memberManagementAllowed(current.membership.role); const member = await addExistingMember(current.organization.id, input.email, input.role); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "organization.member.added", resourceType: "member", metadata: { role: input.role } }); return member; }),
    updateMemberRole: protectedProcedure.input(z.object({ userId: z.number().int().positive(), role: memberRole })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); memberManagementAllowed(current.membership.role); if (input.userId === current.organization.ownerUserId) throw new TRPCError({ code: "BAD_REQUEST", message: "The organization owner role cannot be changed here." }); const member = await changeMemberRole(current.organization.id, input.userId, input.role); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "organization.member.role_updated", resourceType: "member", resourceId: String(input.userId), metadata: { role: input.role } }); return member; }),
  }),
  governance: router({
    overview: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); governanceAllowed(current.membership.role); return getGovernanceOverview(current.organization.id); }),
    updateRetention: protectedProcedure.input(z.object({ researchRetentionDays: z.number().int().min(30).max(3_650), knowledgeRetentionDays: z.number().int().min(30).max(3_650), auditRetentionDays: z.number().int().min(365).max(3_650), legalHoldEnabled: z.boolean() })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); governanceAllowed(current.membership.role); return updateRetentionPolicy(current.organization.id, ctx.user.id, input); }),
  }),
  catalog: protectedProcedure.query(() => INDUSTRY_CATALOG),
  dashboard: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); return dashboard(ctx.user.id, current.organization.id); }),
  tracked: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); return listTrackedIndustries(ctx.user.id, current.organization.id); }),
  setTracked: protectedProcedure.input(z.object({ slug: z.string().min(1).max(96), tracked: z.boolean() })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const industry = getIndustry(input.slug); if (!industry) throw new TRPCError({ code: "BAD_REQUEST", message: "Select an industry from the available catalog." }); await setTrackedIndustry(ctx.user.id, current.organization.id, { slug: industry.slug, name: industry.name, tracked: input.tracked }); return { success: true }; }),
  monitoring: router({
    list: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); return listMonitoredIndustries(ctx.user.id, current.organization.id); }),
    alerts: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); const [alerts, unreadCount] = await Promise.all([listAlerts(ctx.user.id, current.organization.id), unreadAlertCount(ctx.user.id, current.organization.id)]); return { alerts, unreadCount }; }),
    preferences: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); return getMonitoringPreferences(ctx.user.id, current.organization.id); }),
    create: protectedProcedure.input(z.object({ industrySlug: z.string().min(1).max(96), scope: z.string().min(20).max(1_500), cadence: z.enum(["weekly", "monthly"]), riskThreshold: z.enum(["all", "high"]) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const industry = getIndustry(input.industrySlug); if (!industry) throw new TRPCError({ code: "BAD_REQUEST", message: "Select an industry from the available catalog." }); const monitor = await createMonitoredIndustry(ctx.user.id, current.organization.id, { industrySlug: industry.slug, industryName: industry.name, scope: input.scope, cadence: input.cadence, riskThreshold: input.riskThreshold }, sessionFromRequest(ctx.req)); await setTrackedIndustry(ctx.user.id, current.organization.id, { slug: industry.slug, name: industry.name, tracked: true }); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "monitoring.created", resourceType: "monitored_industry", resourceId: monitor.id, metadata: { cadence: input.cadence, riskThreshold: input.riskThreshold } }); return monitor; }),
    update: protectedProcedure.input(z.object({ id: z.string().min(1).max(40), scope: z.string().min(20).max(1_500).optional(), cadence: z.enum(["weekly", "monthly"]).optional(), riskThreshold: z.enum(["all", "high"]).optional(), enabled: z.boolean().optional() })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const { id, ...patch } = input; const monitor = await updateMonitoredIndustry(ctx.user.id, current.organization.id, id, patch, sessionFromRequest(ctx.req)); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "monitoring.updated", resourceType: "monitored_industry", resourceId: id, metadata: { cadence: patch.cadence ?? null, riskThreshold: patch.riskThreshold ?? null, enabled: patch.enabled ?? null, scopeChanged: Boolean(patch.scope) } }); return monitor; }),
    remove: protectedProcedure.input(z.object({ id: z.string().min(1).max(40) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const result = await deleteMonitoredIndustry(ctx.user.id, current.organization.id, input.id, sessionFromRequest(ctx.req)); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "monitoring.removed", resourceType: "monitored_industry", resourceId: input.id }); return result; }),
    runNow: protectedProcedure.input(z.object({ id: z.string().min(1).max(40) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const monitor = (await listMonitoredIndustries(ctx.user.id, current.organization.id)).find(item => item.id === input.id); if (!monitor?.scheduleCronTaskUid) throw new TRPCError({ code: "NOT_FOUND", message: "This monitored industry does not have an active schedule." }); const result = await runMonitoredScan(monitor.scheduleCronTaskUid); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "monitoring.refresh.requested", resourceType: "monitored_industry", resourceId: input.id }); return result; }),
    markAlertRead: protectedProcedure.input(z.object({ id: z.string().min(1).max(40) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); return markAlertRead(ctx.user.id, current.organization.id, input.id); }),
    updatePreferences: protectedProcedure.input(z.object({ inAppEnabled: z.boolean(), dailyDigestEnabled: z.boolean(), minimumSeverity: z.enum(["all", "high"]) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const preferences = await updateMonitoringPreferences(ctx.user.id, current.organization.id, input); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "monitoring.preferences.updated", resourceType: "monitoring_preferences", resourceId: current.organization.id, metadata: input }); return preferences; }),
  }),
  knowledge: router({
    list: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); return listKnowledge(ctx.user.id, current.organization.id); }),
    search: protectedProcedure.input(z.object({ query: z.string().max(160).optional(), tags: z.array(z.string().min(1).max(48)).max(12).optional(), kinds: z.array(z.enum(["insight", "brief", "decision_note"])).max(3).optional(), statuses: z.array(z.enum(["draft", "published"])).max(2).optional() }).optional()).query(async ({ ctx, input }) => { const current = await active(ctx.user); return searchKnowledge(ctx.user.id, current.organization.id, input ?? {}); }),
    createCollection: protectedProcedure.input(z.object({ name: z.string().min(2).max(160), description: z.string().max(2_000).default("") })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const collection = await createKnowledgeCollection(ctx.user.id, current.organization.id, input); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "knowledge.collection.created", resourceType: "knowledge_collection", resourceId: collection.id }); return collection; }),
    createAsset: protectedProcedure.input(z.object({ collectionId: z.string().min(1).max(40).optional(), kind: z.enum(["insight", "brief", "decision_note"]), status: z.enum(["draft", "published"]), title: z.string().min(2).max(220), content: z.string().min(1).max(20_000), tags: z.array(z.string().min(1).max(48)).max(12), scanIds: z.array(z.string().min(1).max(40)).max(12), sourceRefs: z.array(z.string().min(1).max(2_048)).max(48) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const asset = await createKnowledgeAsset(ctx.user.id, current.organization.id, input); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "knowledge.asset.created", resourceType: "knowledge_asset", resourceId: asset.id, metadata: { kind: input.kind, status: input.status, linkedScans: input.scanIds.length, sourceRefs: input.sourceRefs.length } }); return asset; }),
    updateTags: protectedProcedure.input(z.object({ id: z.string().min(1).max(40), tags: z.array(z.string().min(1).max(48)).max(12) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const asset = await updateKnowledgeAssetTags(ctx.user.id, current.organization.id, input.id, input.tags); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "knowledge.asset.tags_updated", resourceType: "knowledge_asset", resourceId: input.id, metadata: { tags: asset.tags.length } }); return asset; }),
  }),
  portfolio: router({
    summary: protectedProcedure.input(z.object({ scanIds: z.array(z.string().min(1).max(40)).max(12).refine(ids => new Set(ids).size === ids.length, "Choose distinct scans.") }).optional()).query(async ({ ctx, input }) => { const current = await active(ctx.user); return portfolioSnapshot(ctx.user.id, current.organization.id, input?.scanIds ?? []); }),
    views: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); return listPortfolioViews(ctx.user.id, current.organization.id); }),
    saveView: protectedProcedure.input(z.object({ name: z.string().min(2).max(160), scanIds: z.array(z.string().min(1).max(40)).min(1).max(12).refine(ids => new Set(ids).size === ids.length, "Choose distinct scans.") })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const view = await savePortfolioView(ctx.user.id, current.organization.id, input); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "portfolio.view.saved", resourceType: "portfolio_view", resourceId: view.id, metadata: { scans: input.scanIds.length } }); return view; }),
    synthesize: protectedProcedure.input(z.object({ scanIds: z.array(z.string().min(1).max(40)).min(2).max(12).refine(ids => new Set(ids).size === ids.length, "Choose distinct scans."), knowledgeAssetIds: z.array(z.string().min(1).max(40)).max(12).default([]), question: z.string().min(12).max(2_000) })).mutation(async ({ ctx, input }) => {
      const current = await active(ctx.user); researchAllowed(current.membership.role);
      const [portfolio, knowledge] = await Promise.all([portfolioSnapshot(ctx.user.id, current.organization.id, input.scanIds), listKnowledge(ctx.user.id, current.organization.id)]);
      const assets = knowledge.assets.filter(asset => input.knowledgeAssetIds.includes(asset.id)).map(asset => ({ id: asset.id, kind: asset.kind, status: asset.status, title: asset.title, content: asset.content, scanIds: asset.scanIds, sourceRefs: asset.sourceRefs }));
      if (assets.length !== input.knowledgeAssetIds.length) throw new TRPCError({ code: "NOT_FOUND", message: "One or more selected knowledge assets are outside the active organization." });
      const packet = { portfolio: { metrics: portfolio.metrics, scans: portfolio.scans.map(scan => ({ scanId: scan.id, industry: scan.industryName, scope: scan.scope, executiveSummary: scan.executiveSummary, sourceIntelligence: scan.sourceIntelligence, emergingRisks: scan.emergingRisks, risks: scan.risks, sources: scan.sources })) }, knowledgeAssets: assets };
      const answer = await answerResearchQuestion({ question: input.question, scanContext: JSON.stringify(packet), history: [], focus: "enterprise_portfolio" });
      await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "portfolio.synthesis.generated", resourceType: "portfolio_synthesis", metadata: { scans: input.scanIds.length, knowledgeAssets: input.knowledgeAssetIds.length } });
      return { answer, metrics: portfolio.metrics, evaluatedScans: portfolio.scans.map(scan => ({ scanId: scan.id, industry: scan.industryName })) };
    }),
  }),
  workspace: protectedProcedure.query(async ({ ctx }) => { const current = await active(ctx.user); return listWorkspace(ctx.user.id, current.organization.id); }),
  scan: protectedProcedure.input(idInput).query(async ({ ctx, input }) => { const current = await active(ctx.user); const result = await getScan(ctx.user.id, current.organization.id, input.scanId); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "This private research scan could not be found." }); return result; }),
  recordReportExport: protectedProcedure.input(z.object({ scanId: z.string().min(1).max(40), format: z.enum(["pdf", "pptx"]) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); const result = await getScan(ctx.user.id, current.organization.id, input.scanId); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "This private research scan could not be found." }); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: input.format === "pdf" ? "export.pdf.generated" : "export.powerpoint.generated", resourceType: "market_scan", resourceId: input.scanId, metadata: { format: input.format } }); return { success: true }; }),
  createScan: protectedProcedure.input(z.object({ industrySlug: z.string().min(1).max(96), scope: z.string().min(20, "Add a research focus of at least 20 characters.").max(1_500), projectName: z.string().max(160).optional() })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const industry = getIndustry(input.industrySlug); if (!industry) throw new TRPCError({ code: "BAD_REQUEST", message: "Select an industry from the available catalog." }); const sources = await collectPublicSources(industry.name); const analysis = await generateMarketScan({ industry: industry.name, scope: input.scope, sources }); const scan = await saveScanPackage(ctx.user.id, current.organization.id, { industrySlug: industry.slug, industryName: industry.name, projectName: input.projectName, scope: input.scope, sources, analysis }); await setTrackedIndustry(ctx.user.id, current.organization.id, { slug: industry.slug, name: industry.name, tracked: true }); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "research.scan.created", resourceType: "market_scan", resourceId: scan.id, metadata: { industry: industry.slug, sources: sources.length, projectNamed: Boolean(input.projectName) } }); return { scanId: scan.id }; }),
  addNote: protectedProcedure.input(z.object({ scanId: z.string().min(1).max(40), title: z.string().min(2).max(220), content: z.string().min(1).max(20_000) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const note = await addNote(ctx.user.id, current.organization.id, input); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "research.note.created", resourceType: "research_note", resourceId: note.id, metadata: { scanId: input.scanId } }); return note; }),
  ask: protectedProcedure.input(z.object({ scanId: z.string().min(1).max(40), question: z.string().min(2).max(4_000), mode: z.enum(["general", "risk"]).optional().default("general") })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const result = await getScan(ctx.user.id, current.organization.id, input.scanId); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "This private research scan could not be found." }); const { sources, analysis } = parseStoredScan(result.scan.sourceJson, result.scan.analysisJson); const context = JSON.stringify({ industry: result.scan.industryName, scope: result.scan.scope, analysis, sources }); const channel = channelForQuestionMode(input.mode); const history = selectConversationHistory(result.messages, channel); const answer = await answerResearchQuestion({ question: input.question, scanContext: context, history, focus: input.mode === "risk" ? "emerging_risks" : "market" }); await addChatTurn(ctx.user.id, current.organization.id, input.scanId, input.question, answer, channel); return { answer }; }),
  exportBrief: protectedProcedure.input(idInput).query(async ({ ctx, input }) => { const current = await active(ctx.user); const result = await getScan(ctx.user.id, current.organization.id, input.scanId); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "This private research scan could not be found." }); const { sources, analysis } = parseStoredScan(result.scan.sourceJson, result.scan.analysisJson); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "export.industry_brief.generated", resourceType: "market_scan", resourceId: input.scanId }); return { filename: `${result.scan.industrySlug}-industry-perspective.md`, content: renderBriefMarkdown(result.scan, analysis, sources) }; }),
  exportCompetitor: protectedProcedure.input(z.object({ scanId: z.string().min(1).max(40), competitorName: z.string().min(1).max(220) })).query(async ({ ctx, input }) => { const current = await active(ctx.user); const result = await getScan(ctx.user.id, current.organization.id, input.scanId); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "This private research scan could not be found." }); const { sources, analysis } = parseStoredScan(result.scan.sourceJson, result.scan.analysisJson); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "export.competitor_profile.generated", resourceType: "market_scan", resourceId: input.scanId }); return { filename: `${input.competitorName.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-competitor-profile.md`, content: renderCompetitorMarkdown(input.competitorName, analysis, sources) }; }),
  exportRiskAnswer: protectedProcedure.input(z.object({ scanId: z.string().min(1).max(40), messageId: z.string().min(1).max(40) })).query(async ({ ctx, input }) => { const current = await active(ctx.user); const result = await getScan(ctx.user.id, current.organization.id, input.scanId); if (!result) throw new TRPCError({ code: "NOT_FOUND", message: "This private research scan could not be found." }); const answer = result.messages.find(message => message.id === input.messageId && message.channel === "risk" && message.role === "assistant"); if (!answer) throw new TRPCError({ code: "NOT_FOUND", message: "This private Risk Q&A answer could not be found." }); const { sources } = parseStoredScan(result.scan.sourceJson, result.scan.analysisJson); await recordAuditEvent(current.organization.id, ctx.user.id, { eventType: "export.risk_brief.generated", resourceType: "market_scan", resourceId: input.scanId }); return { filename: `${result.scan.industrySlug}-risk-qa-brief.md`, content: renderRiskAnswerMarkdown(result.scan, answer.content, sources) }; }),
  compareRisks: protectedProcedure.input(z.object({ scanIds: z.array(z.string().min(1).max(40)).min(2).max(6).refine(ids => new Set(ids).size === ids.length, "Choose distinct scans to compare."), question: z.string().min(12).max(1_500) })).mutation(async ({ ctx, input }) => { const current = await active(ctx.user); researchAllowed(current.membership.role); const results = await Promise.all(input.scanIds.map(scanId => getScan(ctx.user.id, current.organization.id, scanId))); if (results.some(result => !result)) throw new TRPCError({ code: "NOT_FOUND", message: "One or more selected private scans could not be found." }); const comparisonPacket = results.map(result => { const record = result!; const { sources, analysis } = parseStoredScan(record.scan.sourceJson, record.scan.analysisJson); const emergingRisks = analysis.emergingRisks?.length ? analysis.emergingRisks.slice(0, 3) : analysis.risks.slice(0, 3).map((risk, index) => ({ rank: index + 1, title: risk.title, summary: risk.detail, severity: `${risk.likelihood} likelihood / ${risk.impact} impact`, watchSignal: "Monitor the supporting market evidence.", sourceIds: risk.sourceIds })); return { scanId: record.scan.id, industry: record.scan.industryName, scope: record.scan.scope, emergingRisks, sources: sources.map(source => ({ id: source.id, title: source.title, publisher: source.publisher, url: source.url })) }; }); const answer = await answerResearchQuestion({ question: input.question, scanContext: JSON.stringify({ comparisonPacket }), history: [], focus: "risk_comparison" }); return { answer, comparedScans: comparisonPacket.map(scan => ({ scanId: scan.scanId, industry: scan.industry })) }; }),
});
